- Makefile
- bgs/bgs.go
- lex/gen.go
- server/server.go
Nothing urgent here, just getting CI to "green" with current `go vet -a ./...` linting.
The "comment out a big function which isn't used" is definitely debatable. Would be fine adding a CI override comment or something there.
> cleanup some lints

- HACKING.md
- api/atproto/admingetModerationReports.go
- cmd/beemo/main.go
- xrpc/xrpc.go
This polls a PDS instances periodically (default: 30sec) looking for moderation reports since the bot started up. When it finds one, it sends a message to a slack channel via an "incoming webhook". There is basically no state in the bot itself (eg, no database or file with "last seen" info), which makes this simple to deploy.
The way I hacked in admin auth in `xrpc/xrpc.go` probably isn't the best.
> quick and dirty mod report notification bot for slack

- mst/cbor_gen.go
- mst/diff.go
- mst/mst.go
- mst/mst_interop_test.go
- mst/mst_test.go
- mst/mst_util.go
- repo/repo.go
~The tests here work with atproto (Typescript) and adenosine (Rust). They are mostly not working here in golang, mostly because of differences in DAG-CBOR CID formatting (it seems).~
~Also probably going to add some repo-layer tests before this gets merged.~
Updated and now MST tests are passing. Some `testing` (integration) tests are failing in CI, but run ok for me locally. Hrm.
Updated code from typescript implementation. Added cross-language interop tests, with exact CID values. Removed some redundant code and unused struct fields (not sure why `go vet` or similar didn't complain about those).
> MST/repo interop tests; updates to implementation from typescript

- cmd/bigsky/main.go
The motivation here is to have the daemon run securely by default, and we set this flag for, eg, local dev. Instead of insecure by default and we set a flag for production.
> bgs: default to crawling wss://, 'insecure' flag for ws://

- cmd/gosky/main.go
Go 1.16 providers the signal.NotifyContext to remove extra code for processing os signals https://pkg.go.dev/os/signal#NotifyContext
> simplification handling cancelation signal

- api/plc.go
- cmd/beemo/main.go
- testing/utils.go
- xrpc/xrpc.go
Per official documentation, the client must close the response body when finished with it.
Refs: https://pkg.go.dev/net/http#pkg-overview
> all: close http response body

- api/plc.go
- carstore/repo_test.go
- cmd/gosky/util/util.go
- indexer/posts_test.go
- repomgr/ingest_test.go
- testing/utils.go
io/ioutil is deprecated as of Go 1.16.
> remove io/ioutil package

- indexer/keymgr.go
In https://github.com/bluesky-social/did-method-plc/pull/5 there were some updates to how the did doc is laid out in PLC.  I was experiencing an issue with signature checks, and this small update seems to have done the trick.
For good measure, here's the error that was surfacing:
```
2023-03-07T10:59:57.689-0500    ERROR   indexer indexer/crawler.go:158  failed to perform repo crawl of "did:plc:wqzurwm3kmaig6e6hnc2gqwo": importing fetched repo: process new repo: cb errored (54/54): signature check failed: no key found by that ID:
```
> Get signing key from PLC using new did doc semantics

- cmd/fakermaker/main.go
Tagging @dholms for eyes on this trivial change to re-enable use of PNGs for avatars in the fakermaker profile generation code path.
This was fixed yesterday in `atproto` (https://github.com/bluesky-social/atproto/pull/570), and I just tested locally.
If you want to try testing fakermaker against PDS, the current flow would be to run `make run-pds` in atproto repo (maybe need postgresql set up with default auth ahead of time; and `make run-plc` might need to be running as well). In a separate terminal, in `indigo`, create a `.env` file at the top level dir with the low-security default auth settings:
```
BSKY_ADMIN_AUTH=password
ATP_PDS_HOST=http://localhost:2583
ATP_AUTH_HANDLE="admin.test"
ATP_AUTH_PASSWORD="admin"
```
Then run these commands to get through profile generation with the …
> fakermaker: use PNGs for avatars (fixed upstream)

- bgs/bgs.go
- gen/main.go
- notifs/notifs.go
- pds/feedgen.go
- pds/handlers.go
- pds/server.go
- testing/utils.go
I might also soon recommend that we refactor the package itself to `lex/lexutil/`, or top-level `lexutil/`.
> refactor: consistent 'lexutil' naming

- .github/workflows/golang.yml
This seems to be the correct and safe way to enable github actions CI runs for third party forks (when they are submitted as a PR).
The important detail is that the `.github/*` action stuff does not run from the fork, it runs from the previous `main` (or whatever branch) that the fork branched off from. This should prevent exfiltration of secrets?
Still possible for folks to, eg, mine cryptocurrency on our dime, I think. The current behavior from the github UI side should be that first-time contributors need to be approved before the CI job runs.
> ci: run actions on pull_request

- indexer/indexer.go
- repomgr/repomgr.go
The last PR handled this for playback but missed catching when they happen on the fly, also dropped some log warnings to infos so I could see what was even going wrong.
> some extra tweaks required for fully handling 'too big' slices

- carstore/bs.go
- indexer/indexer.go
- repomgr/ingest_test.go
- repomgr/repomgr.go
The source of the bug is the one line change in the carstore, the repomanager changes are the part that could use the closest look, basically i'm allowing the first commit in the gap fill process to dip into the carstore for the blocks it needs for the diff, later diffs are isolated and must pull blocks from the car file.
> fix issue with gap filling in index crawler

- Makefile
- example.dev.env
Switches `make build` back to `go build ./...` for speed. `make binaries` builds all the executables, and `make all` is an alias of that. Maybe a bit non-standard; `go build ./...` could be `make check` instead? But this is my current muscle memory.
Adds a `make lexgen` helper which looks in `../atproto/lexicons/` by default, but can be overridden by `LEXDIR` environment variable.
Adds `make run-dev-bgs` to match current behavior of `make run-pds` in `atproto` repo. This is quite helpful to me for getting local integeration dev work going. Note that the `GOLOG_LOG_LEVEL` environment variable can't currently be definted in `.env` config file because of import ordering.
> makefile: dev runners; fast `make build`; lexgen

- .github/workflows/container-beemo-ghcr.yaml
- .github/workflows/container-labelmaker-ghcr.yaml
- cmd/beemo/Dockerfile
- cmd/labelmaker/Dockerfile
Labelmaker will get deployed in the next week or so.
Beemo is currently running fine on render, but at some point we might want it deployed as a container. I could disable that container build by default if we want to hold off on it.
LMK if I should switch these up to use AWS instead of ghcr.io.
At some point maybe we could abstract these to be less duplication between files, but seems fine for now.
> Additional dockerfiles and github actions: beemo and labelmaker

- carstore/bs.go
- go.mod
- go.sum
The package `github.com/ipfs/go-block-format` is deprecated  and moved to `github.com/ipfs/go-libipfs/blocks`
> github.com/ipfs/go-block-format is deprecated

- xrpc/xrpc.go
probably should also handle chunked encoding..? Though i'm not convinced that should be allowed in xrpc
> error out if we dont read the entire response body

- .github/workflows/golang.yml
- go.mod
Main motivation for upgrading to 1.20 is the reverse proxy improvements in `net/http/httputil`.
> Bump to golang 1.20

- lex/util/decoder.go
- lex/util/decoder_test.go
Small change to have JSON marshaling error instead of panic (segfault). This came up during labelmaker development. Includes tests.
> lex/util: error, not panic, on nil marshaling of LexiconTypeDecoder

- cmd/beemo/main.go
- cmd/fakermaker/main.go
- go.mod
- go.sum
- labeling/hiveai.go
- labeling/micro_nsfw_img.go
- labeling/sqrl.go
- util/http.go
- xrpc/xrpc.go
The initial motivation for this was for beemo to not crash on the very first HTTP 5xx it encounters, but to do a couple retries. An example where we expect occasional 5xx errors is when deploying some of our own services, or running complex database migrations.
I initially was going to hand-roll something simple like https://brandur.org/fragments/go-http-retry, with fixed backoffs, but it seems like the hashicorp lib is fairly light and slots in as a regular `http.Client`, which is nice.
Curious your thoughts on when/where to do this instead of just crashing and having the service restart. I think there are reasonable arguments in a variety of directions; having automatic retries everywhere for 429 and 502/503 has served me well. This could, technically, result in duplicate requests when …
> HTTP retry helper; add as default for XRPC, beemo, labelmaker, fakermaker

- Makefile
- cmd/fakermaker/main.go
- fakedata/accounts.go
- fakedata/generators.go
- fakedata/localinterop_test.go
- testing/pds_fakedata_test.go
- util/http.go
Refactored fakermaker to move internal methods in to `fakedata/` package.
Then use that to write integration tests.
Some code duplication here, though note that it can be helpful to comment out parts of the complete fakermaker run when pieces are not supported.
The `const` variable under `./testing` will probably need to change.
> fakermaker integration tests, both internal and against typescript (running locally in dev mode)

- lex/util/decoder_test.go
- mst/diff.go
- mst/mst_test.go
Small leftover review things from the weekend.
I assume the deleted function was used in a test or defensive programming previously, but it is unused and I think best to just remove it.
The `TestNewFromType` function is also never used and could just be deleted instead of tested.
> small test coverage improvements

- cmd/gosky/main.go
Small hack that was needed for manually registering a did:plc with a recovery key.
> gosky: command to output did:key for an input key file

- lex/util/cbor_gen_test.go
- lex/util/lex_interop_old_test.go
- lex/util/lex_interop_test.go
- lex/util/lex_types_test.go
This matches up with the test vectors in: https://github.com/bluesky-social/atproto/pull/734
There was a single previous test file that i've renamed and split into interop and generic test cases. I kept the old interop test case versions (which didn't end up merged in `atproto`) around in a separate file.
Note that for golang I declared actual struct types (schemas) for these types, instead of doing generic parsing.
The "array" case (with arrays-of-arrays-of-bytes) does not work with golang cbor-gen currently, so I only have JSON tests for that.
I didn't do the "poorly formatted" test case yet, I wanted to get the basic tests in place quickly for now. It might be helpful to add a blob in that test case as well, to test generic (schema-less / struct-less) blob CID extraction.
> lex: another interop test (unicode, blobs, etc)

- bgs/bgs.go
- bgs/fedmgr.go
I thought that our linter would have caught this, but apparently it only catches certain shapes of this bug.
Probably worth auditing the rest of the codebase for this problem at some point (or just wait for the go team to fix it like jake said they might)
> fix loop closure issue

- cmd/gosky/main.go
The lexicon changed from an option string to an array of strings, this is just catching up to that properly.
> fix invites command when not targeting a user

- Makefile
- cmd/fakermaker/README.md
- cmd/fakermaker/docker-compose.yaml
- cmd/fakermaker/docker-create-dev-dbs.sql
- util/http.go
These don't run fully-automated yet, but this is a step towards additional end-to-end inter-language tests.
For now there is a single small/simple fakermaker test which runs only against the PDS.
Planned follow-ups:
- actual end-to-end tests: golang test code to talk to BGS or appview in addition to just PDS, checking that events came through
- automation of having the appview connect to BGS, and BGS connect to PDS
- additional PDS instances on separate ports, to test things like account migration
- some solution for DID and handle resolution with fake domains. maybe it will just work with HTTP resolution (vs DNS)?
- PDS configured to proxy requests to the appview
> docker-compose integration tests

- mst/mst_test.go
- mst/mst_util.go
goos: darwin
goarch: arm64
pkg: github.com/bluesky-social/indigo/mst
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
IsValidMstKey-8   301.1n ± 4%   262.8n ± 4%  -12.69% (p=0.000 n=10)
│   before   │               after                │
│    B/op    │   B/op     vs base                 │
IsValidMstKey-8   32.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=10)
│   before   │                after                │
│ allocs/op  │ allocs/op   vs base                 │
IsValidMstKey-8   1.000 ± 0%   0.000 ± 0%  -100.00% (p=0.000 n=10)
> mst: remove an alloc in isValidMstKey

- xrpc/xrpc.go
- xrpc/xrpc_test.go
Currently the `makeParams` function will take a string slice and URL encode it as `[hello+world]` instead of `hello,world` which makes the XRPC API upset (HTTP:400 errors) since it wants a comma separated list of strings. This change tries to cast the params interface into a string slice, and if it matches, it does a join instead of just printing the debug value string into the query params.
Tested in the [GraphBuilder](https://github.com/ericvolp12/bsky-experiments/blob/main/pkg/events/helpers.go#L20) and hasn't broken anything, not sure if/what the testing plan is here.
That function previously threw 400s trying to talk to the XRPC API.
That project is using a [module replace](https://github.com/ericvolp12/bsky-experiments/blob/main/go.mod#L107) to test my commit in place of the …
> Join string slices in makeParams to fix broken urlencodes

- mst/mst.go
- mst/mst_test.go
- mst/mst_util.go
goos: darwin
goarch: arm64
pkg: github.com/bluesky-social/indigo/mst
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
LeadingZerosOnHash-8   72.28n ± 3%   58.76n ± 2%  -18.71% (p=0.000 n=10)
│   before   │               after                │
│    B/op    │   B/op     vs base                 │
LeadingZerosOnHash-8   48.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=10)
│   before   │                after                │
│ allocs/op  │ allocs/op   vs base                 │
LeadingZerosOnHash-8   1.000 ± 0%   0.000 ± 0%  -100.00% (p=0.000 n=10)
> mst: remove alloc in leadingZerosOnHash

- HACKING.md
- Makefile
* Fix help for new lexgen make target.
* Drop mention of `goimports` from HACKING. (I think not needed with @bradfitz's changes in [#137](https://github.com/bluesky-social/indigo/pull/137))
* Mention possibly needing to update ./gen/main.go after `make lexgen`.
* Fix a couple typos in HACKING.
I was also tempted to try to add slightly more text to HACKING.md (or maybe include a link to my other PR in #150 as an example of lexgen-related munging), but I guess let's see if that other PR is even remotely correct 😅 .
> make/HACKING: fix make help and minor improvements to HACKING

- bgs/admin.go
- bgs/bgs.go
- bgs/fedmgr.go
- cmd/bigsky/main.go
- indexer/indexer.go
- labeler/service.go
- util/uri.go
Adding the scaffolding for a simple admin token auth for control routes. 
Actual routes TBD, but just wanting to land the auth first as a separate thing.
> add simple auth for new admin routes and basic auth token management

- go.mod
- go.sum
Updates github.com/ipld/go-car to the latest commit to bring in https://github.com/ipld/go-car/pull/420 which should drop allocated bytes (garbage that triggers the GC to spend CPU) by about 9%.
> go.mod: bump github.com/ipld/go-car to latest

- bgs/admin.go
- bgs/bgs.go
- carstore/bs.go
- cmd/gosky/main.go
- events/dbpersist.go
- events/events.go
- events/persist.go
- indexer/indexer.go
- repomgr/repomgr.go
- testing/integ_test.go
- testing/utils.go
- xrpc/xrpc.go
Adds a basic admin route to fully take down a given repo, including marking the user as 'taken down' and fully deleting all associated data.
> implement repo takedowns

- mst/mst_test.go
- mst/mst_util.go
And optimize it a bit, so the Go compiler can avoid some bounds checks.
benchstat:
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
CountPrefixLen-8   78.85n ± 1%   38.45n ± 5%  -51.23% (p=0.000 n=10)
│   before   │             after              │
│    B/op    │    B/op     vs base            │
CountPrefixLen-8   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│   before   │             after              │
│ allocs/op  │ allocs/op   vs base            │
CountPrefixLen-8   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
> mst: make countPrefixLen match JavaScript's UTF-16-edness

- cmd/palomar/README.md
Tried to clean up the README. Also found an error with the default username for es. You may not appreciate the choices, and that's fine. I was going over the code to test it out and it just didn't seem as clean as I'd go for.
> clean up README.md, fix default username

- cmd/bigsky/main.go
- events/events.go
- labeler/service.go
- pds/server.go
- testing/utils.go
This is a pre-refactor refactor for some work i'm going to do on the event persister, the channels here make it difficult to implement batched persisting so i'm pulling those out now, and then will do the rest in a separate PR
> use fewer channels in outbound events loop

- pds/server.go
- testing/integ_test.go
- testing/labelmaker_fakedata_test.go
- testing/pds_fakedata_test.go
- testing/utils.go
This patch makes PDS boot on a random port in the integration tests.
It's a first step towards #165 ("Integration tests need randomly
assigned ports") and request for feedback on its strategy before I apply
it to BDS.
To do this work, we have to teach `pds.Server` how to boot with an
existing net.Listener and teach its Echo instance to do the same. That
required using `Echo#StartServer` instead of `Echo#Start`. Using
`Echo#StartServer` seems to be the accepted pattern for booting from an
existing Listener in Echo and both it and `Start` call the same
`Echo#configureServer` under the hood.
PDS isn't a production service right now, but I believe I've reproduced the 
configuration that echo would have done that there wouldn't be production 
impact. However, if BGS is, we could talk about …
> support booting PDS on a random port in testing

- bgs/bgs.go
- testing/integ_test.go
- testing/labelmaker_fakedata_test.go
- testing/utils.go
This patch makes BGS boot on a random port in the integration tests.
To do this work, we have to teach `bgs.Server` how to boot with an
existing net.Listener and teach its Echo instance to do the same. That
required using `Echo#StartServer` instead of `Echo#Start`. Using
`Echo#StartServer` seems to be the accepted pattern for booting from an
existing Listener in Echo and both it and `Start` call the same
`Echo#configureServer` under the hood.
Along the way, we refactor the uses of the `TestBGS.host` field into a
`TestBGS#Host` method.
Fixes #165
> support booting BGS on a random port in testing

- bgs/bgs.go
- pds/handlers.go
- pds/server.go
- repomgr/ingest_test.go
- repomgr/repomgr.go
Running the diff is pretty expensive, and the primary issue that could come up with trusting the pds ops is that they could leave out ops referencing records being added, which seems like a bit of a non-attack as its just the pds inconveniencing its own users.
> Avoid using mst diff to calculate ops, trust pds

- cmd/bigsky/main.go
- events/dbpersist_test.go
- indexer/posts_test.go
- labeler/service.go
- pds/server.go
- repomgr/bench_test.go
- repomgr/dbheadstore.go
- repomgr/ingest_test.go
- repomgr/memheadstore.go
- repomgr/repomgr.go
- testing/utils.go
The in-memory variant goes about 20% faster in the benchmark. The rest is carstore costs
> extract headStore to make it easier to swap out database

- cmd/sonar/main.go
- sonar/metrics.go
- sonar/sonar.go
This should make it easier to filter dashboards between environments and eventually allow for sonar to connect to multiple sockets at a time and emit distinct metrics from each socket.
> Track socket connection URL in Sonar metrics

- api/extra.go
- cmd/gosky/debug.go
Cleaning up a deprecation to ioutil.ReadAll, ioutil.WriteFile.
it's deprecated to go1.16.
> Replace deprecated ioutil.ReadAll, ioutil.WriteFile

- pds/server.go
Cleaning up a deprecation warning that popped up in my editor while
working on other things. xerrors has marked itself as deprecated for Go
versions 1.13 and later.
> use errors.Is instead of xerrors.Is

- carstore/bs.go
This route is already cached, but when we have a cache miss its currently a ~2 second query because its doing an index scan on the primary key index. Dropping the deleted_at implicit condition helps reduce this to ~500ms which is a good gain (unfortunately doesnt show up in any benchmarks because this is only slow at scale).
If this ever ends up being a problem, the simple solution is to add an extra index, but that makes the write path slower which I don't really want to do right now.
> avoid deleted_at condition, add note for further improvements

- api/extra.go
if handle resolution failed via a bad http response code, we wouldnt get that info
> better logging when handle resolution fails

- util/time.go
- util/time_test.go
i'm surely missing some that are *Technically* valid, but i'd prefer we just got more strict on whats allowed.
> add in smarter timestamp parsing

- bgs/fedmgr.go
- testing/integ_test.go
There might be other test failures as a result of this, but i ran them 20 or so times and this was the only one that popped up locally.
We might want to make the settings on the consumer pool tuneable, but for now this should get us some much better numbers on our load testing
> use parallel event processor in bgs

- bgs/bgs.go
- bgs/fedmgr.go
- cmd/bigsky/main.go
- repomgr/dbheadstore.go
Bumping the cursor in the DB for every event has become a bottleneck on event throughput.
To ameliorate this, we can batch cursor updates and flush them to the DB every 10 seconds.
> Batch cursor updates for PDSs

- cmd/gosky/admin.go
Adds a flag `--print-handles` to print handles in an invite tree
> Add flag to print invite tree handles

- .gitignore
- Makefile
- cmd/supercollider/Dockerfile
- cmd/supercollider/main.go
- events/metrics.go
- go.mod
- go.sum
This change refactors Supercollider to support two different modes: Reload and Fire.
In Reload mode, Supercollider generates a specified number of events as quickly as it can and writes the CBOR to a file. It uses in-memory SQLite for the repo manager and I've benched it at around 2.2k evt/sec for generation.
The static file includes creation of the repos and all the repo appends for lots of Posts. 2 Million events takes around 16 minutes to produce. We call this a loaded magazine.
In Fire mode, Supercollider will fire the magazine of events at any client that connects to the subscribe repos endpoint. Since we're reading from a file, we can go as fast as the socket can handle, though we also accept a flag to limit emission rate if we want to for any reason.
This method allows us to get …
> Refactor Supercollider to have Reload and Fire modes for higher burst emission

- cmd/beemo/main.go
- cmd/bigsky/main.go
- cmd/fakermaker/main.go
- cmd/gosky/main.go
- cmd/labelmaker/main.go
- cmd/laputa/main.go
- cmd/sonar/main.go
- cmd/supercollider/main.go
- go.mod
- go.sum
Match MAXPROCS to Container CPU quota with Automaxprocs to improve go's scheduler decisions: https://github.com/uber-go/automaxprocs
> Use automaxprocs to improve goroutine scheduling in containers

- bgs/bgs.go
Consumer timeout checking is great but if we're playing back a TON of events, the ping ends up deep in a backlog and out 5 second timeout on the ping doesn't make sense so let's keep track of the last time we successfully wrote to the consumer and only try to ping if it's been 30 seconds since our last write.
> Only ping a consumer if we haven't written _anything_ in a while

- bgs/bgs.go
- carstore/bs.go
- indexer/crawler.go
- indexer/indexer.go
- repomgr/ingest_test.go
- repomgr/repomgr.go
- testing/integ_test.go
- testing/utils.go
This fixes two things, first the test-pds didnt properly implement rebases which caused some issues in tests. 
The second thing was that old blockRefs werent getting deleted after the rebase, despite their associated CarShards getting deleted.
> fix cleanup of rebases in carstore

- pds/server.go
Hey there - I'm trying to build out an E2E test suite based on the PDS implementation included here.
It looks like `com.atproto.server.createSession` has the JWT Auth middleware running on it, which prevents me calling this RPC in order to log in. As far as I can tell, the handler has been implemented for this RPC correctly (`pds/Server.handleComAtprotoServerCreateSession`) - it's just not possible to call it.
> Skip JWT middleware for `com.atproto.server.createSession` RPC in PDS

- bgs/bgs.go
- cmd/bigsky/main.go
- cmd/labelmaker/main.go
- cmd/laputa/main.go
- cmd/palomar/main.go
- cmd/supercollider/main.go
- pds/handlers_test.go
- util/cliutil/util.go
Network latency has a massively bad impact on subscribe throughput right now, we suspect it might be due to write buffer sizes on the websocket connection.
> Use a bigger write buffer for consumer websockets

- .github/workflows/container-beemo-ghcr.yaml
- .github/workflows/container-bigsky-aws.yaml
- .github/workflows/container-bigsky-ghcr.yaml
- .github/workflows/container-labelmaker-ghcr.yaml
- .github/workflows/container-palomar-aws.yaml
- .github/workflows/container-palomar-ghcr.yaml
Counterpart: https://github.com/bluesky-social/atproto/pull/1460
This PR runs the actions only for the original `bluesky-social/indigo` repository on the `main` branch.
It also contains very minor workflow cleanup for consistency.
Do not merge if you wish to build and push main branches from other repositories.
> Require bluesky-social/indigo for Container Build & Push

- go.mod
- mst/mst_util.go
This was about a 2x gain for me on my laptop, using go v1.20, for the hot `BenchmarkLeadingZerosOnHash` method (called on every key inserted in to a MST):
```
bnewbold@snocat:~/code/indigo/mst$ go test -run '^$' -bench=. -run=^#
goos: linux
goarch: amd64
pkg: github.com/bluesky-social/indigo/mst
cpu: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
BenchmarkIsValidMstKey-8        	64364982	       17.11 ns/op	      0 B/op	      0 allocs/op
BenchmarkLeadingZerosOnHash-8   	6786610	      175.9 ns/op	      0 B/op	      0 allocs/op
BenchmarkDiffTrees-8            	     72	 18111121 ns/op	11194858 B/op	 121144 allocs/op
BenchmarkCountPrefixLen-8       	51624517	       21.88 ns/op	      0 B/op	      0 allocs/op
---
bnewbold@snocat:~/code/indigo/mst$ go test -run '^$' -bench=. -run=^#
goos: linux …
```
> mst: use sha256-simd for hashing

- carstore/bs.go
- repo/cbor_gen.go
- repo/repo.go
- repomgr/ingest_test.go
- repomgr/repomgr.go
We won't need this until the sync changes that remove history land.
This adds tracking of which blocks are no longer referenced during processing of a new commit. We then delete the carstore references for those blocks when accepting that commit.
Work still to be done is figuring out how we want to compact old shard files.
It seems relatively straightforward to do the compaction as a post-process step that queries recently changed repos and checks if enough block references have been dropped to make it worth running a repo compaction. (in writing this, im thinking we might want a 'stale' flag on blockRefs that we set to true instead of deleting them).
When compacting, to make the read paths more efficient, we should leave the most recent several car slices alone and only compact the …
> track no longer referenced blocks, delete refs

- atproto/syntax/aturi.go
- atproto/syntax/aturi_test.go
Somehow had the `String()` method defined in the test file instead of `aturi.go` by mistake.
> atproto/syntax: hotfix for ATURI String()

- bgs/bgs.go
- cmd/gosky/main.go
if we try to gift invite codes to more than a few hundred users at a time, it fails because the request body is too big.
> split up createInvite batch calls

- atproto/identity/base_directory.go
This is the documented behavior, but implementation was not working correctly for the base resolver.
> identity: invalid/missing handle for LookupDID is not an error, just an invalid handle

- atproto/identity/base_directory.go
- atproto/identity/handle.go
- atproto/identity/identity.go
And specifically, skip it by default for `.bsky.social` (we only do HTTP resolution). This reduces unnecessary DNS traffic, especially with higher concurrency/parallelism.
> identity: support skipping DNS resolution for some domain suffixes

- api/plc.go
- bgs/bgs.go
- did/multi.go
- did/web.go
- plc/caching.go
- plc/fakedid.go
When a handle update happens, we check the PLC entry to get the new handle, but if we've cached the did document for a user, we will have the old doc and fail to process the handle change.
> Implement a selective cache flush interface for handle updates

- atproto/syntax/atidentifier.go
- atproto/syntax/atidentifier_test.go
- atproto/syntax/aturi.go
- atproto/syntax/aturi_test.go
This was something we discussed a couple weeks back: making access to sub-fields of ATURI more ergonomic.
This embraces the reality of "empty" values in golang and will return empty values instead of a `nil` pointer and error when the field doesn't exist, or if it fails to parse. I'm not really sure how I feel about it; feels vaguely unsafe? Maybe we need "IsEmpty()" helpers on all these, or something?
Still open to a `ATURIParts` or similarly named `struct` version of URI, with the various components as accessible fields; that could be in addition to this PR.
> syntax: ATURI ergonomics

- bgs/bgs.go
- models/models.go
Newer DIDs with valid handles invalidate existing DIDs with the same handle
We check for handle validity when creating an External User which means this handle _should_ be more recently valid than whatever we might have in our database.
> Handle conflicts with handles

- bgs/bgs.go
- carstore/bs.go
- cmd/gosky/bgs.go
compaction on rapidly changing repos is slow and 99% of the time is spent in deleteShard. This speeds it up a little bit, from there we can look at what else gets in the way.
> do shard deletions in batches

- ts/bgs-dash/src/components/Dash/Dash.tsx
We only support this route via POST now so I'm updating the admin dash to work properly with it.
> Fix request crawl from BGS Admin Dash

- bgs/bgs.go
- bgs/handlers.go
- bgs/stubs.go
This change implements a few more `com.atproto.sync.*` endpoints in the BGS.
After this PR we'll need to figure out Blobs and the Listing endpoints.
For `ListRepos` we should just be able to walk through the DB in some consistent order (maybe by UIDs).
> Implement some unimplemented Atproto Sync BGS Handlers

- carstore/bs.go
turns out you cant pass infinitely sized arrays to your sql driver.
> split up batches of deletes during compaction

- bgs/admin.go
- bgs/bgs.go
- carstore/bs.go
- carstore/repo_test.go
The main idea here is to have each shard contain twice the number of blocks as the next shard, under the logic that older shards will need to be rewritten less and also accessed less in general.
still to discuss, should there be a max size on shards?
> improved compaction, minimize shard count while minimizing IO

- bgs/bgs.go
- carstore/bs.go
- cmd/gosky/debug.go
- indexer/indexer.go
If for some reason we end up with missing data, add a multi-stage fallback to first fetch the missing revision range ( in the case of an event slice erroring) and then if data is still missing, fall back to fetching the entire repo.
also added a debug command to fetch and verify data in a repo.
> in the case of missing blocks, fall back to full repo fetch

- carstore/bs.go
turns out some repos have *a lot* of shards and this makes sql unhappy.
> break up requests for block refs

- atproto/identity/cache_directory.go
- atproto/identity/live_test.go
- search/firehose.go
This change uses a `sync.Map` to coalesce requests for the same DID or Handle during a lookup to prevent lots of requests for the same content from going out before the first one comes back to get cached.
> Coalesce requests for the same DID or Handle in Directory

- bgs/admin.go
- bgs/fedmgr.go
- indexer/indexer.go
im not entirely happy with the flow here, feels kinda jank. The main thing we want to do is just keep trying if the event sync fails instead of returning an error (which results in the users repo getting behind until they send another event).
> if catching up on buffered jobs fails, fallback to getRepo

- search/parse_query.go
- search/parse_query_test.go
I haven't tested against an actual index, but there is a parsing test, and i'm pretty confident this will resolve the `from:blah` issue.
> palomar: default q to '*' when there is only filter

- bgs/bgs.go
- events/diskpersist_test.go
- indexer/indexer.go
- models/models.go
- pds/handlers.go
- pds/server.go
- repomgr/repomgr.go
We still want to index repos with invalid handles, it should be the downstream consumer's responsibility to validate a handle, especially cause it can change and become invalid without a new HandleChange event being emitted. These events are just hints that you should go grab the DID doc for this user cause it may have changed.
> Allow crawling repos that have invalid handles

- bgs/admin.go
- bgs/bgs.go
- carstore/bs.go
- carstore/repo_test.go
- cmd/gosky/bgs.go
- cmd/gosky/debug.go
- mst/mst.go
- repomgr/repomgr.go
if a deleted block matches multiple blockRefs in a given repo, we can't safely assume its no longer referenced. The 'correct' way to move forward is to do a full repo traversal to enumerate the 'correct' set of blocks referenced in the MST, but that requires more thought and is actually something that needs to be done at the repo manager level (and involves extra locking and other shenanigans that i dont want to implement just yet).
So for now, we add duplicate blocks to the keep set and just assume they are still being referenced somewhere.
> for now, add duplicate stale refs to the keep set

- bgs/bgs.go
seems like this should hopefully be allowed for testing, and the main combination we want to prevent is SSL (ie prod) BGS with non-SSL PDS...?
> BGS: allow non-SSL BGS with SSL PDS

- bgs/bgs.go
- bgs/metrics.go
- carstore/bs.go
- cmd/gosky/main.go
- repomgr/repomgr.go
a small grab-bag of changes, most things are either tweaking a batch size or adding an attribute to a trace.
The one 'real' change here is falling back to an individual block read instead of a prefetch if the shard in question is over a size limit.
> more trace attributes and some tweaks

- atproto/identity/base_directory.go
- atproto/identity/handle.go
- atproto/identity/live_test.go
Quick addition to DNS handle resolution to allow configuring a set of fallback DNS servers which will be tried after regular DNS and (optional) authoritative DNS.
Haven't tested super carefully. Does seem kind of aggressive to do all these DNS queries for *every* failed DNS lookup, but we can tweak at larger scale if needed.
> identity: add fallback DNS servers

- api/atproto/synclistRepos.go
- bgs/bgs.go
When resyncing with a PDS, if users are active then the CID we get from `ListRepos` can become out of date by the time we start comparing the CIDs against our local repo heads (i.e. new events come in for some users, we update the repo head in our local Carstore, and our CID is fresher than the one in-memory from `ListRepos`).
Since the Repo Rev is monotonically increasing, we can use the Rev we get back from `ListRepos` as a "low-water-mark" such that, if our local Rev for that repo is > the one we get from the PDS, we know we're current. This should reduce the number of unnecessary repos being recrawled during a resync.
> Resync with a PDS by comparing revs insted of commit CIDs

- atproto/identity/base_directory.go
- atproto/identity/handle.go
- atproto/identity/identity.go
- atproto/identity/live_test.go
- atproto/identity/mock_directory_test.go
- atproto/syntax/handle.go
Realized this wasn't being enforced at resolution time like it should be. These are allowed in *syntax* but not at resolution time.
Also adds the `.example` and `.alt` TLDs, and defines invalid handle as a constant (requested earlier). (updating spec doc and typescript impl in parallel)
closes: https://github.com/bluesky-social/indigo/issues/306
> disallow invalid handle TLDs

- search/firehose.go
- search/indexing.go
This change adds verbose logging to Palomar handle updates and resolves handles from PLC when seeing an update instead of trusting the handle from the event.
> Add verbose logging to palomar handle updates

- cmd/palomar/main.go
- search/query.go
These are tweaks to search quality, mostly typeahead, with no change to index schema (so no reindexing needed). A couple basic fixes, and then some boosting and rescoring hacks.
I tested these by having local palomar query the prod search index over an SSH tunnel. I didn't check query latencies, but nothing was crazy slow, and based on the changes i'm fairly confident there won't be a significant latency hit for typeahead. Profile search may get a bit slower.
There are some remaining quality issues we will probably want to revisit, but would probably require re-indexing. Eg, we are not doing any stemming at all on fulltext fields (my bad!). This will impact profile descriptions, but in particular posts.
> Palomar profile search improvements

- carstore/bs.go
writing and loading large amounts of individual staleRefs is a bit slower than it should be. Since we only ever access them all at once, storing them as a single row makes things a lot easier, especially on the write path (the indexes get pretty large and inserting into them many times gets expensive)
> combine all staleRefs for a given operation into a single record

- cmd/gosky/admin.go
Adds error handling so we can iterate through an entire invite tree even if it contains accounts that have been taken down or otherwise error out on getRepo.
> Add error handling for listInviteTreeCmd

- LICENSE-APACHE.txt
- LICENSE-MIT.txt
- LICENSE.txt
- README.md
Had consensus on this from discussion a week or two back. Copied the license files and general structure from did-method-plc (which we updated months ago), with very minor grammar updates and link fixes.
Notified external contributors and getting sign-offs in this issue thread: https://github.com/bluesky-social/indigo/issues/403
Will give that a couple days before merging (unless :100: reply sooner).
> Update indigo source license to MIT/Apache2

- bgs/bgs.go
- models/models.go
When users change their handles, that change doesnt necessarily propagate through the whole world consistently. The big issue this causes for us is if a user changes their handle from X to Y, and we arent able to validate it, we dont update our accounting of that change. Then if a new user creates an account with handle X, we fail to correctly initialize that user because of the uniqueness constraint.
I think I'll have to manually do these migrations, i doubt gorm will correctly swap the indexes from unique to not-unique.
I read through all the code referencing unique conflicts and handle setting and I believe this should work just fine.
> drop unique constraint on handles

- events/dbpersist.go
- indexer/indexer.go
The `blocks` field is required to be present in order to pass validation in the typescript code.
> ensure 'blocks' field is set in tooBig events

- carstore/bs.go
I spaced the fact that we include proper dag-cbor cid links to images which are not actually included in the car slices. In the case where someone drops a reference to an image (deletes an image post, or updates their profile picture) then we would hit this 'ipld not found' error on the image cid (since we never got it in the first place).
Here, we skip any CID that isnt CBOR, This is a reasonable assumption to make for now, unless we start dangling random cbor graphs off of the MST, at which point ill probably need to get more clever (I'd really rather not).
> only traverse cbor blocks when running mst diff

- events/events.go
right now if these buffers fill up we just start dropping events, and then when the buffers drain we just resume sending events. this seems quite wrong.
> drop consumers if their out buffer fills up

- cmd/gosky/main.go
used this for testing the bugfix PR earlier
> make testing slow consumers easy

- xrpc/xrpc.go
This provides the caller additional info, in particular about rate limits. (Unless they're using `util.RobustHTTPClient()`)
> Extract additional info from HTTP response into the returned error

- api/atproto/serverrefreshSession.go
this value is typed as "unknown" in lexicon, which we don't really know how to map into a go type here
> temporarily remove the did doc field from auth response

- util/http.go
- xrpc/xrpc.go
This is a simplest possible approach to pass through hitting a rate limit to the application that uses the default XRPC client.
It's a design question if this is what you want to have. Alternatives include:
* Gate this behaviour change behind a flag in `xrpc.Client` struct
* Allowing to specify a threshold for the duration until rate limit reset, below which the client would keep the current behaviour
FWIW, JS client seems to not have any retry logic in place.
> Tell RobustHTTPClient to treat rate-limiting as non-retryable error

- api/extra.go
- cmd/gosky/admin.go
- cmd/gosky/did.go
- cmd/gosky/main.go
handle resolution is currently failing on things using this method because the PDS check here is just wrong.
> handle resolution does not depend on any xrpc routes

- bgs/bgs.go
We kick off slow consumers, but apparently forgot to actually close the connection. I think this oughta be all we need
> properly close websocket when we terminate the connection

- LICENSE.txt
The underlying motivation is that pkg.go.dev can't detect our license combination, and refuses to show docs w/o a known license.
This change is based on looking at how https://github.com/ipfs/kubo formats their license file, and checking with the 'licensecheck' golang package.
> license: change formatting so licensecheck detects better

- backfill/backfill.go
- carstore/bs.go
- carstore/repo_test.go
- cmd/gosky/main.go
- repo/repo.go
- repomgr/repomgr.go
- testing/sig_test.go
The slightly more correct approach would be to ignore specifically the prev cid failure in CalcDiff, but doing so would require a bunch of plumbing that will quickly become irrelevant.
> if repo base has a 'prev', ignore block diff errors

- atproto/crypto/testdata/signature-fixtures.json
This tests for DER-encoded signatures, which we don't want to allow. The typescript implementation was accepting these, but now doesn't, which is why there are new test entries.
> atproto/crypto: add test fixtures

- atproto/identity/base_directory.go
- atproto/identity/cache_directory.go
- atproto/identity/mock_directory.go
I'm not sure why the error wasn't getting returned; might have been a typo? Probably worth re-reading that function again in review. I hit a nil de-reference pointer in automod caused by that function returning `nil, nil`.
> identity: small improvements

- repo/tid.go
Third call on the same microsecond would not match the `if` condition and would return the same value as the first call.
> Fix TID generator to avoid duplicates

- .gitignore
- automod/countstore/countstore.go
- automod/countstore/countstore_mem.go
- automod/countstore/countstore_redis.go
- automod/countstore/countstore_test.go
- automod/engine.go
- automod/engine_test.go
- automod/rules/fixture_test.go
- automod/rules/identity.go
- automod/rules/interaction.go
- automod/rules/promo.go
- automod/rules/replies.go
- cmd/hepa/server.go
- go.mod
- go.sum
A few minor hopefully-advancements to the automod/hepa packages:
- `countstore` is now extracted as a package.
- Synchronization primitives are added to MemCountStore.  This fixes crashes when running `hepa` without the use of Redis.
- Additional testing, to make sure that MemCountStore gets enough exercise that the race detector has something to work on in tests.
- Attempted to sneak in some docs along the way!
The diff looks a little larger than it is, because of git and file moves... but individual commits are broken down as much as possible, so those should also be fine to review in isolation if preferred.
> automod: extracting some packages, and concurrency safety

- automod/rules/all.go
These are just too noisy right now, turning up client bugs much more often than intentionally misleading content.
May come back to these later; definitely leaving code (and tests) in place.
> automod: remove mistleading url+mention rules from default list

- api/atproto/repodescribeRepo.go
- api/atproto/servercreateAccount.go
- api/atproto/servercreateSession.go
- api/atproto/servergetSession.go
- api/atproto/serverrefreshSession.go
- lex/gen.go
This is a bit more robust than the current situation where we manually comment things out.
Just looks for the specific field names `didDoc` or `plcOp` and plops in an `*interface{]` type instead for those.
Could also have done `*map[string]interface{}` but I was worried not initializing that datatype; maybe unwarranted. 
My assumption is that `json.RawMessage` would be best here for JSON stuff, but that causes problems for CBOR stuff.
> lexgen: slightly more robust 'unkown' handling (hack)

- automod/rules/interaction.go
A number of folks seem to end up doing manual follow/unfollow interaction pairs at around 550/day. The most obvious/suspicious automated actors do around 1000/day.
This is a trivial one-liner so intend to self-merge.
> autmod: bump interaction churn quota to 800

- automod/action_dedupe_test.go
- automod/circuit_breaker_test.go
- automod/countstore/countstore_test.go
- automod/engine.go
- automod/event.go
- automod/report.go
- automod/rules/interaction.go
The motivation here is to start auto-reporting in production based on specific rules. Specifically, this PR would start reporting on interactions churn (follow/unfollow), letting human mods confirm before taking action on an account.
Before we do that, need to de-duplicate reports. For example, if an account creates thousands of spammy posts, only want to report the account once. Generally want to prevent run-away rules from creating millions of reports, or doing thousands of automated account takedowns (for example).
This PR prevents re-reporting based on daily counters (fast checks), as well as double-checking against the mod service API just before filing a report (slower, but reliable).
This PR also adds "quotas" for mod actions, implemented using the counter system. This isn't …
> automod: action limits; create reports for interaction churn

- bgs/handlers.go
This is a work-around for the specific situation in: https://github.com/bluesky-social/atproto/issues/1949
We may need to have lexgen stubs ensure that any required array types in Output types are set to an explicit empty array, instead of nil? I haven't dug in to the details of JSON marshaling and CBOR marshaling to understand the scope of this issue yet, but the root of the issue is that the typescript code is being more strict about "empty" types than golang is. The typescript strictness seems both correct and reasonable to me, FWIW.
> relay: return explicit empty array, not nil, for sync.listRepos

- lex/gen.go
- lex/util/decoder.go
Working on a separate patch to explicitly handle `ErrUnrecognizedType` in automod firehose consumer, and reviewed this file.
> lexgen error handling tweaks

- atproto/identity/cache_directory.go
This is closely related to https://github.com/bluesky-social/indigo/pull/458, which tried to resolve an issue with DIDs. I was seeing very confusing behavior with handles; was able to confirm `"", nil` getting returned internally on real-world lookups.
I took a more aggressive approach and changed the return signatures of both update helper methods to just return an "Entry", not as a pointer, and no err. This makes the code flow much simpler.
I tacked on a special control-flow error message as defensive programming after getting bit twice on this (darn self!). Probably isn't necessary and smells a bit but :shrug:.
> identity: refactor cache directory to prevent nil/nil condition

- atproto/identity/base_directory.go
- atproto/identity/cache_directory.go
- atproto/identity/did.go
- atproto/identity/did_test.go
- atproto/identity/handle.go
- atproto/identity/identity.go
- atproto/identity/live_test.go
- atproto/identity/mock_directory_test.go
Root motivation here was that a bunch of remote errors were trickling up as full errors when doing identity resolution (via DID), while in reality they should result in "invalid.handle".
I didn't want to just force everything in to ErrHandleNotFound, so I created some new error types (and renamed a couple existing types), and ensured that we were using errors.Is() for matching. This way downstream code can distinguish between "not found" and "error during resolution" when calling the lower-level methods, if they care (eg, a debugging tool or interface would care). Also wrapped the errors instead of just returning, so additional context couple be tacked on the message.
There are still some situations where the root cause might be a local error (like local wifi) as opposed to a remote error …
> identity: refactor error hierarchy and error handling

- api/atproto/servercreateSession.go
The did doc is defined as an `any` type in the lexicon right now, which in all other cases implies a record (with a $type field). For now, lets just ignore this in the go code (its not necessary for anything) until we figure out a better way forward.
> dont include did doc in create session for now

- automod/rules/keyword.go
- automod/rules/replies.go
- skip short post text for identical replies
- start reporting bad word records for review
The "short post text" instead of skipping just empty also handles a common case of "handful of emoji".
> quick tweaks to rules at scale

- automod/rules/all.go
- automod/rules/mentions.go
- automod/rules/spammentions.go
Introduce a simple new rule for detecting and flagging spikes of mentions within a period.
> automod: mentions spike rule

- automod/account_meta.go
- automod/cachestore/cachestore.go
- automod/cachestore/cachestore_mem.go
- automod/cachestore/cachestore_redis.go
- automod/directory/redis_directory.go
- automod/engine.go
- automod/event.go
- automod/flagstore/flagstore.go
- automod/flagstore/flagstore_mem.go
- automod/flagstore/flagstore_redis.go
- automod/flagstore/flagstore_redis_test.go
- automod/flagstore/flagstore_test.go
- automod/setstore/setstore.go
- automod/testing.go
- automod/util/strings.go
- cmd/hepa/main.go
- cmd/hepa/server.go
Several more package extractions.
These are all the easy ones -- flagstore, cachestore, setstore, directory -- all get yanked out in the same way as countstore already was.
These didn't cause any major changes to package graph overall, it just makes the main automod package smaller (yay).  Near future targets are to try to tug engines and events a bit further apart, and that might be more complicated, so I thought I'd put up the easy-to-review diffs first.
> automod orga

- cmd/hepa/main.go
- cmd/hepa/server.go
This works around a current issue in prod where actions are failing to persist because the session expires.
The real fix for the underlying issue (IMHO) is to re-implement `xrpc.Client` to handle this in a more elegant and robust way. That is sort-of tracked in https://github.com/bluesky-social/indigo/issues/378
I was initially confused why this was only coming up when taking actions, because the client is used for a number of reads (GET) as well. Those GETs mostly use *admin* auth (a token in the HTTP Authorization header), not login/session auth (which requires refresh), which explains why it mostly works, then fails for actions.
> hepa: periodically refresh auth session

- api/atproto/admindefs.go
- api/atproto/adminsendEmail.go
- api/atproto/repodescribeRepo.go
- api/atproto/servercreateAccount.go
- api/atproto/servercreateSession.go
- api/atproto/servergetSession.go
- api/atproto/serverrefreshSession.go
- api/atproto/temptransferAccount.go
- api/bsky/notificationlistNotifications.go
- cmd/lexgen/main.go
As a temporary hack, just skip the `com.atproto.temp.importRepo` endpoint which uses Lexicon features that lexgen does not support.
There are a small number of actual lexicon updates, but the main motivation here is to handle *all* of the `didDoc` and `plcOp` fields. That is also a hack for now, but this resolves a number of regressions, eg with refreshSession.
> lexgen update

- atproto/syntax/cid.go
- atproto/syntax/datetime.go
- atproto/syntax/did.go
- atproto/syntax/language.go
- atproto/syntax/tid.go
- search/indexing.go
Lots of CPU time spent compiling reused regexps in CPU profiles
> Move all regexp MustCompiles outside

- api/extra.go
- util/http.go
These packages emit log lines from all kinds of services, even those not using go-log, and they end up formatted inconsistently (lines not JSON).
> library package go-log to slog update

- automod/engine/blobs.go
- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/engine.go
- automod/engine/persist.go
- automod/engine/ruleset.go
- automod/engine/ruletypes.go
- automod/pkg.go
- automod/rules/all.go
- automod/rules/blobs.go
- automod/visual/abyss_api.go
- automod/visual/abyss_client.go
- automod/visual/abyss_rule.go
- automod/visual/doc.go
- automod/visual/hive_rule.go
- automod/visual/hiveai.go
- automod/visual/hiveai_client.go
- automod/visual/hiveai_rule.go
- automod/visual/hiveai_test.go
- automod/visual/testdata/hiveai_resp_example.json
- cmd/hepa/main.go
- cmd/hepa/server.go
This is just porting over existing auto-labeling stuff from appview in to the automod framework.
New engine-level supporting features:
- new "blob" rule function type
- ruleset fetches blobs from upstream PDS, if necessary
- `Effects` can track blob-level takedowns (CDN purges) as part of record takedowns
> automod visual auto-labeling, and abusive image scanning

- automod/capture/capture_test.go
- automod/engine/action_dedupe_test.go
- automod/engine/circuit_breaker_test.go
- automod/engine/engine.go
- automod/engine/persisthelpers.go
These were from earlier API design, and are just confusing now.
> engine: remove wrapper counter and set methods

- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/engine.go
- automod/engine/ruleset.go
- automod/engine/ruletypes.go
- automod/pkg.go
- automod/rules/all.go
This is prep work to get automod inserted in to our push notification service as a library.
Relatively small PR, which is great.
Open questions:
- what should response to the notification service look like? here I proposed just a boolean (false for no change, true to reject the message)
- what other context and info is available? working with the original notification types might be good, though they only really exist in "view" form (with extra hydrated metadata), not as a record or something like that. probably at least the "Reason" and an AT-URI reference?
> automod: notification rules/processing

- automod/engine/engine.go
- automod/engine/fetchaccountmeta.go
- automod/engine/persist.go
- automod/engine/ruleset.go
Saw a bunch of errors in prod, stemming from some federation tests and failure to fetch account metadata (eg, profile).
We should support partial-success and partial-processing in most cases, except for internal errors. This updates a lot of error throws to log-and-continue, and updates a bunch of remaining error throws to have better descriptions.
> automod: iterate on error handling

- Makefile
- carstore/bs.go
- cmd/bigsky/main.go
- cmd/gosky/bsky.go
- cmd/gosky/main.go
- cmd/stress/main.go
- events/dbpersist.go
- fakedata/generators.go
- labeler/admin.go
- lex/util/lex_interop_old_test.go
- lex/util/lex_interop_test.go
- notifs/notifs.go
- pds/feedgen.go
- pds/handlers.go
- testing/car_did_repro_test.go
- testing/feedpost_test.go
- testing/utils.go
Pretty straight-forward, we do this in other repos. Run *all* `go vet` rules, not just a fixed list (the default is all rules).
> lint: use default 'go vet' settings

- bgs/admin.go
- cmd/gosky/bgs.go
currently this will always default to 20 when called (despite the comment saying 50), which is better for our purposes than the 50 that defaults in the background routine, but still should be something we can set
> make shard threshold parameter usable through admin api

- cmd/hepa/consumer.go
- cmd/hepa/server.go
Fixes data race.  Was probably harmless in practice, as these values are best-effort anyway, but keeping the race detector clean and happy when engaged is highly valuable for maintainability in the long run.
Some comments attached about the field's concurrency.
> hepa: use atomics for lastSeq.

- atproto/identity/did.go
- atproto/identity/handle.go
I think these were embarrassing oversights?
For PLC in particular, want to keep HTTP/2 connections open for reuse. Less of a thing for the well-known lookups, though for the common case of `*.bsky.social` lookups, there are lots of hostnames, but all the same backing server, so hopefully still works.
`did:web` we might actually want a separate connection every time.
> identity: use shared http.Client for lookups, and close resp bodies

- cmd/hepa/main.go
Hepa already has an http service for prometh metrics, and it's the http package's default one, so this continues to just dogpile on that.
With the defaults, http://localhost:3989/debug/pprof/ is now informative.
Also added nudges to the runtime to enable block profiling and mutex profiling.  Without these nudges, those reports are empty.
I picked the rate numbers here somewhat capriciously; they may need tuning to keep impact down in prod, or we may end up needing knobs for toggling this at runtime.  We'll see.
(The goroutine profiles alone, requested periodically, provide a decent sampling of data that can be used to infer some things about blocking anyway, even if that pprof feature isn't enabled explicitly!  But more data is almost always better, so I propose turning it on for now.)
> hepa: add pprof endpoint, and enable block profiling.

- README.md
This PR updates the two links in README.md that point to `blueskyweb.xyz` to the equivalent `bsky.social` URLs.
Also, I noticed that Line 13 still refers to 'Big Graph Service', should this be updated to 'Relay'?
https://github.com/bluesky-social/indigo/blob/c72ce2340db3cc99fc886c2284daf19e438c7b91/README.md?plain=1#L13
> Update `blueskyweb.xyz` links in README.md to `bsky.social`

- search/indexing.go
- search/server.go
- search/transform.go
I took a peek at prod error logs and found some issues:
- deleting search documents is failing, because the "document ID" (docID) was formatted wrong, because the `rkey` parameter is actually a full path, not just the record key part
- many actually-valid datetimes were not getting parsed correctly, resulting in posts not having correct createdAt, likely resulting in them not appearing with expected ranking in search results
- many HTTP 404 errors on fetches of base path; not really a big deal but might as well return healthcheck
I haven't tested these much yet, we should probably deploy to staging (which consumes the prod firehose, IIRC) and observe that for a bit.
> palomar: prod errors burndown

- automod/capture/fetch.go
- automod/capture/testing.go
- automod/engine/action_dedupe_test.go
- automod/engine/blobs.go
- automod/engine/circuit_breaker_test.go
- automod/engine/context.go
- automod/engine/engine_test.go
- automod/engine/ruleset.go
- automod/rules/hashtags_test.go
- automod/rules/keyword.go
- automod/rules/keyword_test.go
- automod/rules/misleading_test.go
- cmd/hepa/consumer.go
This shifts the external API for automod from taking a pre-parsed "any" struct of a record, to taking CBOR bytes. the motivation is to make it easier to work with content for which the lexicon isn't know at compile time, which will soon become much more common as we allow folks to write arbitrary record types to their repositories, and this content shows up on the relay firehose.
The `atproto/data` package knows how to parse and extract some information from generic atproto record CBOR, so it is able to pull all the blobs (`$type: blob` objects nested within records), and we can switch over to that, which is more generic (and hopefully robust) than doing schema-by-schema extraction.
For firehose content, this is all pretty straight-forward, because the records are already coming in as …
> automod: defer parsing

- backfill/gormstore.go
The backfiller fails to flush operations when it doesn't identify an event as stale if its `rev` is equal to the last seen `rev`. This gets caught as a discontinuity, and it returns an error:
```
2024/02/05 18:25:18 ERROR failed to flush buffered ops source=backfiller_buffer_flush repo=[repo] error="event since did not match current rev (3kkpf3r7lx22m != 3kkpf53gjgs24): buffered event revs did not line up"
```
which blocks the rest of the buffered events from being processed, and the job is eternally marked as enqueued.
> Fixed backfill GormJob.FlushBufferedOps not skipping final stale event

- backfill/backfill.go
Resolves issue raised in https://github.com/bluesky-social/indigo/issues/595
Double checked with https://github.com/ericvolp12/atp-looking-glass to see what's coming through the firehose for `since` and `prev` fields and yep this was my bad.
> Check for since, not prev, when backfilling

- atproto/identity/identity.go
For labelers we need to specify which service public key we grab.
> atproto/identity: add PublicKeyFor method

- atproto/identity/base_directory.go
- atproto/identity/identity.go
- atproto/identity/redisdir/redis_directory.go
- automod/capture/capture.go
- automod/capture/testdata/capture_atprotocom.json
- automod/engine/fetch_account_meta.go
- automod/rules/quick.go
- automod/rules/testdata/capture_hackerdarkweb.json
The main thing here is removing the cached ("pre-parsed") key in the identity doc. I think this was non-trivial overhead when doing lots of lookups, and required manual override when serializing (actually caching!) the objects. I don't think we relied on the key parse caching for performance anywhere; if actual profiling shows we need it, should add as a private field, or cache externally.
`PublicKeyFor` read a bit weird and non-idiomatic to my eyes so I updated to `GetPublicKey(id)`, and added a service endpoint equivalent. If this is too nit-picky or the method is being used a bunch elsewhere (branches?) can revert that bit.
> identity: remove ParsedPublicKey caching; tweak get/parsing method names and doc-comments

- search/query.go
- search/transform.go
This tries to mitigate issues with bogus createdAt timestamps in post records. In particular this might (?) be causing a bunch of network traffic in-app when you search posts for "hello".
We have a batch of these in the current index which mess up ranking, so there is a query-time filter. A better mitigation would be to run a cleanup "update by query" which might look like this (untested):
```
POST palomar_post/_update_by_query
{
"script": {
"source": "ctx._source.created_at = null",
"lang": "painless"
},
"query": {
"range": {
"created_at": {
"gte": "2024-01-01"
}
}
}
}
```
Our PDS currently enforces a reasonable createdAt, but it might stop this Lexicon-specific behavior some day (speculative), or third-party PDS implementations might not take this step. So this PR adds checks at …
> palomar: handle bogus future createdAt better

- HACKING.md
- Makefile
- cmd/bigsky/Dockerfile
- cmd/bigsky/README.md
- cmd/hepa/consumer.go
- cmd/hepa/main.go
- cmd/hepa/server.go
- cmd/supercollider/main.go
- testing/integ_test.go
- testing/utils.go
not very high-priority, but noticed these doing some palomar work and did a cleanup.
didn't want to touch the actual bgs package and bigsky code base.
the CLI arg parsing stuff makes it easy to keep the old env vars around, which means this shouldn't impact deploys with old config.
> update more BGS/Relay terminology

- Makefile
- cmd/palomar/Dockerfile.opensearch
- cmd/palomar/README.md
- cmd/palomar/README.opensearch.md
- cmd/palomar/main.go
- search/firehose.go
- search/japanese.go
- search/japanese_test.go
- search/post_schema.json
- search/query.go
- search/query_test.go
- search/server.go
- search/testdata/transform-post-fixtures.json
- search/transform.go
This is just for posts right now, not profiles (descriptions, display name, etc).
I'm somewhat confident in the indexing approach (separate duplicate fields, gated by text detection). And this seems to work ok for simple cases.
I'm not very confident about all-kanji text and indexing, and mixes of Japanese and non-english character sets. For example, Japanese and Korean (CJK), or Japanese and Thai (non-CJK).
One positive thing is that everything is still being indexed in the regular text fields, using the existing analysis pipeline. So we can revert the query changes if needed, or improve some corner cases using query-time-only techniques.
Closes: https://github.com/bluesky-social/indigo/issues/628
> palomar: special-case Japanese text indexing using kuromoji

- search/parse_query.go
- search/parse_query_test.go
has a bit of test coverage which gives me confidence, but haven't done any other testings. blast radius seems small.
closes: https://github.com/bluesky-social/atproto/issues/2028
> search: allow at-prefixed handle with "from:"

- api/bsky/actorsearchActorsTypeahead.go
- api/bsky/feedsearchPosts.go
- api/bsky/unspeccedsearchActorsSkeleton.go
- api/bsky/unspeccedsearchPostsSkeleton.go
- cmd/palomar/main.go
- go.mod
- go.sum
- search/handlers.go
- search/parse_query.go
- search/parse_query_test.go
- search/post_schema.json
- search/profile_schema.json
- search/query.go
- search/query_test.go
- search/testdata/transform-post-fixtures.json
- search/transform.go
- search/url.go
- search/url_test.go
TODO:
Closes: https://github.com/bluesky-social/indigo/issues/191
Closes: https://github.com/bluesky-social/indigo/issues/593
> palomar: refactor query string parsing; updates to schemas and transform

- automod/engine/engine.go
- automod/engine/persist.go
- cmd/hepa/main.go
- cmd/hepa/server.go
We don't actually need the "ozone" client to have a session via password; it just uses admin auth and provides DID as CreatedBy arg when emitting events. It can also talk directly to the Ozone instance.
The PDS admin client also is admin-auth only, and talks to entryway (optional).
> automod: refactor 'admin' and Ozone clients

- backfill/backfill.go
- backfill/backfill_test.go
- backfill/gormstore.go
- backfill/memstore.go
(Part of https://github.com/bluesky-social/indigo/issues/638)
This utilizes constants from the `repomgr` package for buffered operations.
This was already the case, actually, as they were used [here](https://github.com/bluesky-social/indigo/blob/main/backfill/backfill.go#L241), I just added them throughout the code.
They're also used to check the operations emitted by the firehose: https://github.com/bluesky-social/indigo/blob/main/backfill/backfill.go#L469-L471
The firehose, in turn, uses the events emitted by the repo manager for the `Action` field in firehose events: https://github.com/bluesky-social/indigo/blob/main/indexer/indexer.go#L83-L94
This brings us full circle:
Repo manager emits diff operations -> firehose repo commit ops `.Action` -> backfill buffered op `.kind`
Notably, …
> backfill: use constants for bufferedOp.kind

- bgs/admin.go
- bgs/bgs.go
- bgs/fedmgr.go
- cmd/palomar/docker-compose.yml
- testing/utils.go
- ts/bgs-dash/src/components/Dash/Dash.tsx
This change adds a per-day new PDS limiter (which can be admin overridden) allowing us to loosen the process around federating new PDSs without risk of being overrun with tons of fraudulent PDSs in a short time.
Admin interface updates include a way to view and update this limit:
> Per-day new PDS limiter to allow less constrained federation

- xrpc/xrpc.go
https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/server/createInviteCode.json
> com.atproto.account.createInviteCode has been renamed to com.atproto.server.createInviteCode

- backfill/backfill.go
- backfill/gormstore.go
- backfill/memstore.go
(part of #638)
This exports the `backfill.BufferedOp` struct to make it possible to implement a custom `Store` and corresponding `Job`.
I've also renamed the fields slightly for easier understanding, and added some documentation.
> backfill: export BufferedOp

- search/query.go
Just sketching, didn't even test this against a local index
> palomar: 'OR' for single-token profile searches

- bgs/bgs.go
Currently we end up with millions of goroutines waiting on semaphores during a full PDS resync if we run against all production PDSs, this fix waits for the semaphore _before_ spawning the goroutine reducing allocs and the size of the stack significantly.
> Acquire semaphore outside of goroutine for resyncs

- carstore/bs.go
If the relay gets shut down very suddenly and things arent properly synced to disk (I think this only happens if there are unexpected power failures on the host machine) then we can get into weird states where some repos have corrupted shard files. 
They keep functioning fine at a high level, but compaction gets impacted and prevented from finishing.
These repos should really just get wiped and resynced, but this change should prevent them from wreaking havoc in the compaction engine.
> keep going if we encounter corrupted shard files

- carstore/bs.go
Returning the errors while soft ignoring them only means we dont finish the rest of the compaction cleanup work in these cases
> more effectively ignore file not found errors in delete path

- cmd/gosky/bgs.go
motivation here is that we are shutting down sandbox. pointing it at prod feels like it would be confusing for other devs.
> gosky: default localhost relay, not sandbox

- cmd/gosky/admin.go
- cmd/gosky/handle.go
- cmd/gosky/main.go
probably more of this to come, the ProdHandleResolver type is basically broken now
> fix handle resolution in some cli commands

- .gitignore
- Makefile
- README.md
- bgs/bgs.go
- cmd/bigsky/README.md
- cmd/bigsky/crawl_pds.sh
- cmd/bigsky/main.go
- cmd/bigsky/sync_pds.sh
- indexer/indexer.go
- Makefile command to build dashboard
- small refactors and simplifications of bigsky env var and CLI arg parsing; should be safe to merge and deploy to prod
- disable some Relay features by default when bigsky is run (like "aggregations" and "spidering")
The helper bash scripts are a bit duplicate with `gosky` commands, and aren't super important, I can yank those if they seem too redundant.
> relay: code tweaks, README, and helper scripts for self-hosting

- bgs/fedmgr.go
The main thing here is `DefaultRepoLimit`. Also bumped the other numbers a bit to be consistent.
> relay: bump default repo limit configuration

- cmd/bigsky/main.go
Increases the default timeout for generic PDSs when running GetRepo from the Relay.
> Increase PDS repo fetch timeout

- bgs/bgs.go
- bgs/fedmgr.go
- cmd/bigsky/README.md
- cmd/bigsky/main.go
- cmd/bigsky/sync_status_pds.sh
- testing/utils.go
This has some low-impact doc and scripts changes, and a couple actually-impactful changes to Relay code:
- I think fixes a bug/type with per-PDS, per-second event rate limits
- wires through some concurrency and limit values as env vars; should not impact the default behaviors
- updates PDS resync numbers (in database and results from API) much more frequently, but doesn't log for all those updates. only impacts actual PDS resync processes
> more relay hosting tweaks

- api/ozone/moderationdefs.go
- api/ozone/moderationemitEvent.go
- api/ozone/moderationqueryStatuses.go
- automod/cachestore/cachestore_redis.go
- automod/countstore/countstore_redis.go
- automod/engine/account_meta.go
- automod/engine/context.go
- automod/engine/engine_ozone.go
- automod/engine/fetch_account_meta.go
- automod/engine/persist.go
- automod/engine/ruleset.go
- automod/engine/ruletypes.go
- automod/flagstore/flagstore_redis.go
- automod/pkg.go
- automod/rules/all.go
- automod/rules/harassment.go
- automod/rules/misleading.go
- cmd/hepa/consumer.go
- cmd/hepa/consumer_ozone.go
- cmd/hepa/main.go
- cmd/hepa/server.go
This has automod consume events from Ozone and feed them in to the rules engine, similar to firehose events. It uses the queryEvents endpoint, polling every 5 seconds. This is all optional; if an ozone admin client isn't configured, it doesn't happen.
- some types of ozone events on an account subject result in account metadata getting flushed. this ensures that, eg, manually-added labels or takedowns end up in automod-visible cached account metadata
- harassment protection rule is updated to look in private tag state from ozone, not just a deployed config JSON file. this was actually more complex than I would thought, and results in additional account metadata fetches, but those are all cached (with cache purging!) so should be fine
- private/admin account metadata queries go to ozone, …
> automod consuming ozone events

- cmd/bigsky/main.go
> fix nil pointer exception on creating account, when relay is self-hosted

- Makefile
- cmd/lexgen/main.go
- lex/gen.go
cross-package references can now make a type know that it needs to include a type field
> lexgen runs all packages together

- automod/engine/account_meta.go
- automod/engine/engine_ozone.go
- automod/engine/fetch_account_meta.go
- automod/engine/persist.go
- automod/pkg.go
- automod/rules/harassment.go
- automod/rules/helpers.go
- automod/rules/helpers_test.go
- automod/rules/identity.go
- automod/rules/mentions.go
- automod/rules/nostr.go
- automod/rules/promo.go
- automod/rules/quick.go
- automod/rules/replies.go
- automod/rules/reposts.go
- cmd/hepa/server.go
these are cleanups related to an earlier bug when rolling out account creation timestamp handling in automod
> automod: fix automod account age

- automod/rules/all.go
- automod/rules/replies.go
adds a spam label to accounts that are under 24 hours doing this, otherwise just reports. maybe too hasty on the label, can adjust. (note our client really doesn't make it easy to make an identical post multiple times in a row like this, where even failures will usually close the composer anyway, so its likely to be intentional). same could probably be applied for same author but with a maybe higher limit
> add `IdenticalReplyPostSameParentRule` to automod

- bgs/compactor.go
This is #742 with additional feature of half the compactor workers pop randomly from the backlog
> multi-threaded compactor with randomness

- cmd/goat/net.go
- cmd/goat/record.go
- cmd/goat/repogetRecord.go
- cmd/goat/repolistRecords.go
Little hack to make `goat` work better with generic record data, aka when we don't know the Lexicon. In this context, just dumping the JSON to stdout (pretty printed).
Sharing b/c we might want to do this generally, at least for API endpoints: `json.RawMessage` instead of `lexutil.LexiconTypeDecoder` when we encounter `unknown` schema type. Note that this won't work for records, and the schema rules do allow `unknown` in records, it just hasn't happened yet.
Another place we encounter this is DID documents, which don't even have `$type` in the JSON.
> goat: generic record data

- backfill/backfill.go
- cmd/supercollider/main.go
- indexer/indexer.go
- repomgr/repomgr.go
This ensures that only one larger allocation is done instead of multiple small ones, reducing pressure on the garbage collector.
> Pre-allocate ops slices that are appended in a loop where possible.

- automod/capture/testing.go
- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/engine.go
- automod/engine/reroute.go
- automod/engine/ruleset.go
- automod/engine/ruletypes.go
- automod/pkg.go
- automod/rules/all.go
- automod/rules/ozone_persist.go
- cmd/hepa/consumer.go
- cmd/hepa/server.go
These are refactors to the `ozone-account-events` branch that we went through together in a pair-programming session.
I haven't re-reviewed these yet, and there are a couple TODOs, but it at least compiles.
> automod: ozone account history refactors

- automod/rules/identity.go
- bgs/bgs.go
- bgs/fedmgr.go
- cmd/athome/handlers.go
- cmd/hepa/server.go
at least in datadog, the structured logging 'host' field clobbers host metadata for the log line.
this might not impact loko, but seems reasonable to just avoid the naming collision generally.
> don't use 'host' as structured logging field

- carstore/bs.go
- carstore/meta_gorm.go
- carstore/util.go
This should be the "no functional change, just code moving" change.
Future change likely to be making an interface and alternative implementation.
> refactor carstore meta into a class

- atproto/syntax/atidentifier.go
- atproto/syntax/aturi.go
- atproto/syntax/cid.go
- atproto/syntax/datetime.go
- atproto/syntax/did.go
- atproto/syntax/handle.go
- atproto/syntax/language.go
- atproto/syntax/nsid.go
- atproto/syntax/recordkey.go
- atproto/syntax/tid.go
- atproto/syntax/uri.go
Was getting "doesn't match regex" for trivial empty-string situations. having shorter more descriptive errors helps debugging.
> syntax: clearer error for trivial empty string case

- mst/mst.go
See also: https://github.com/bluesky-social/atproto-website/pull/346
> mst: clarify in comment that fields are nullable, not optional

- cmd/goat/account.go
- cmd/goat/account_migrate.go
- cmd/goat/account_plc.go
- cmd/goat/auth.go
- cmd/goat/bsky.go
- cmd/goat/bsky_prefs.go
- cmd/goat/identitygetRecommendedDidCredentials.go
- cmd/goat/identitysignPlcOperation.go
- cmd/goat/identitysubmitPlcOperation.go
- cmd/goat/main.go
- cmd/goat/pds.go
- cmd/goat/repo.go
This PR adds support for account migration using the goat CLI tool two different ways:
- a bunch of account helper commands which individually enable doing an account migration: creating a new account using service auth and old DID; migrating all the data; swapping identity around
- a helper command that automates all this (starting with a PLC op auth token)
The hope is that the migrate command should work in common cases, but the individual commands allow cleaning up in the case of partial success, and doing more complex stuff.
Missing pieces as future work:
- `did:web` functionality
- detection of current progress and only continue work that needs continuing (eg, don't try to re-create new account if it already exists and can auth with provided credentials)
- proper support for …
> goat account migration

- backfill/backfill.go
This is pretty drive-by, i'm basically going through our public code and removing direct requests against the entryway (`https://bsky.social/xrpc/...`). It might be more appropriate here to resolve to the user's actual PDS, not sure.
> backfill: checkout from relay, not entryway

- atproto/identity/cache_directory.go
- atproto/identity/handle.go
- atproto/identity/metrics.go
- atproto/identity/redisdir/live_test.go
- atproto/identity/redisdir/redis_directory.go
- cmd/hepa/main.go
A bunch of cleanups and bug fixes.
The biggest fix is to apply a bug fix from the cache directory resulting in "nil/nil" responses. These were fixed in https://github.com/bluesky-social/indigo/pull/479, but not copied to the redis directory implementation, which has the same coalescing code. This recently impacted @whyrusleeping's use in discover. This is a backwards-compatible fix.
Another fix handles cached error messages. An empty string was being stored for the DID. Because redis cache serializes, and the de-serialized DID is re-parsed, the empty strings fail to parse, resulting in an error. I guess we could consider having text parsing of DIDs not actually parse the string? but that would break auto-validation when it is expected. The fix was to make that field nullable. this might …
> identity/redisdir: various fixes

- automod/engine/account_meta.go
- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/fetch_account_meta.go
- automod/engine/metrics.go
- automod/engine/persist.go
- automod/engine/persisthelpers.go
@foysalit: this is part of https://github.com/bluesky-social/indigo/pull/740
I pulled out the record-level ack and escalation for now, for simplicity, even though it will probably be necessary for that other branch to get merged.
> automod: account ack and escalation

- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/metrics.go
- automod/engine/persist.go
- automod/engine/persisthelpers.go
- automod/rules/gtube.go
I want to test this (eg, in staging) with example rules for both accounts and records before merging. But adding for visibility, in case we need this for other rules sooner.
> automod: engine support for adding tags

- automod/engine/account_meta.go
- automod/engine/cid_from_cdn_test.go
- automod/engine/fetch_account_meta.go
- automod/engine/util.go
smol change. couple of new rules need avatar cids. currently have to fetch from public api before the rule processes in a separate request which is meh, since we have the info here already.
> Add avatar to `AccountMeta`

- automod/keyword/tokenize.go
- automod/keyword/tokenize_test.go
There are some cases where it's useful to tokenize a string while _not_ splitting on some non-letter chars like `#`, `*`, `-`, or `_`. Unfortunately right now `Tokenize` will split on all of these, making some matching difficult.
This just adds a second `TokenizeTextSkippingCensorChars` for those particular use cases. Also adding `TokenizeTextWithRegex`, so that other cases can be easily covered in the future if they arise.
> support tokenize while keeping common censor chars

- lex/gen.go
- lex/type_schema.go
This tries to resolve the situation discovered in https://github.com/bluesky-social/indigo/pull/785, with the ozone "upsertSet" procedure.
That lexicon specifies the input schema via reference, instead of an "object" schema in-place.
This code could use real review, I just banged on it until it worked for the current lexicon.
> lexgen: handle 'ref' as procedure input type

- cmd/goat/account_migrate.go
- cmd/goat/actorgetPreferences.go
- cmd/goat/actorputPreferences.go
- cmd/goat/bsky_prefs.go
- cmd/goat/record.go
- cmd/goat/repocreateRecord.go
- cmd/goat/repoputRecord.go
Fixes: https://github.com/bluesky-social/indigo/issues/784
> goat: schema-flexible record creation, and prefs mgmt

- bgs/bgs.go
- cmd/bigsky/main.go
Want to be able to tweak this manually so we can turn it higher during off-peak if necessary
> make compaction worker count configurable

- atproto/identity/identity.go
- limits on HTTP idle connections. mostly impacts did:web and HTTPS handle resolution, which can otherwise result in huge numbers of sockets hanging around (one per custom domain) when operating at scale. values chosen should not have too bad an impact on PLC usage, though we might want to split out separate PLC and non-PLC HTTP clients at some point
- drop some timeouts
> identity package default tweaks

- cmd/rainbow/Dockerfile
- cmd/rainbow/main.go
- splitter/splitter.go
- moving service config towards "rainbow" away from "splitter"
- adds env vars for more config options
- defaults and tweaks for some config options
- add a root path HTTP handler, which is helpful for debugging
> rainbow service setup tweaks

- bgs/fedmgr.go
We see some jerk when the Relay restarts caused by high concurrency of event processing for some high traffic hosts, where some in-progress event handlers die while the cursor is advanced ahead of them and the next event for that repo triggers a catch-up/resync of the repo. This change rewinds the cursor a bit on reconnect to smooth out that process.
> Rewind cursor a bit before reconnection for some relay hosts to smooth over reconnection

- bgs/handlers.go
my bad! had snuck in that recently, `response` is nil if there is an error.
> fix a segfault when passing on requestCrawl fails

- atproto/syntax/cmd/atp-syntax/main.go
- atproto/syntax/did.go
we are apparently burning a bunch of CPU on this regex in prod, so let's bypass for the most common case (valid did:plc).
Would be nice to have a benchmark demonstrating perf gains (or not).
I did some manually testing with the CLI helper and inserted `panic()` statements to confirm that valid DID PLC stays on fast path, and other DIDs don't.
Feedback welcome if there is a more idiomatic/performant golang way to do this... this is still doing unicode stuff, I assume, and maybe casting to bytes would be faster? though probably doesn't impact the actual hot path much. `strings.ContainsAny` or `strings.ContainsFunc` could be used here I guess but :shrug:
> syntax: ParseDID performance

- backfill/backfill.go
- search/indexing.go
The main motivation here is that non-archival relay is returning a 4xx error for fetching repos, and we want to try fetching those from the actual PDS when that happens. This code adds a new code branch when a relay CAR fetch fails to do an identity lookup to find the account's PDS instance, and fetches the CAR from there.
For the search code specifically, it re-uses an existing identity directory, to reduce double-resolution.
This also refactors how fetch URLs are constructed to use just hostnames.
UPDATE: should probably *not* merge this to `main` until Jaz can review
> backfill: add failback to fetch CAR file from PDS (if relay errors)

- indexer/repofetch.go
this needs to be a full lock, not just an R-lock because _sometimes_ it writes to the value
> fix RWLock usage

- carstore/nonarchive.go
fixes "struct literal uses unkeyed fields" in lint.
> Use keyed field in DbCID initialization.

- bgs/bgs.go
- carstore/bs.go
- carstore/nonarchive.go
- cmd/bigsky/main.go
- indexer/indexer.go
- pds/server.go
- repomgr/bench_test.go
- repomgr/ingest_test.go
- repomgr/repomgr.go
- testing/integ_test.go
- testing/utils.go
real jank right now, but doesnt keep all the repo data, just does basic event validation
> non-archival relay

- atproto/syntax/path.go
- atproto/syntax/path_test.go
helper for parsing a repo path (combination of collection and rkey) in to separate NSID and RecordKey
> syntax: path parsing helper

- api/agnostic/actorgetPreferences.go
- api/agnostic/actorputPreferences.go
- api/agnostic/doc.go
- api/agnostic/identitygetRecommendedDidCredentials.go
- api/agnostic/identitysignPlcOperation.go
- api/agnostic/identitysubmitPlcOperation.go
- api/agnostic/repoapplyWrites.go
- api/agnostic/repocreateRecord.go
- api/agnostic/repogetRecord.go
- api/agnostic/repolistRecords.go
- api/agnostic/repoputRecord.go
These are some variants of "typed" atproto sync/repo helpers from `api/atproto` which use `json.RawMessage` instead of the lexutil `LexiconTypeDecoder` wrapper.
These are mostly used from tools like `goat` which work with arbitrary record data, when we don't have lexgen types (or they aren't imported, or whatever). They can also be used for things like preferences, where the type in an open union is rapidly changing, and we don't want to "clobber" (drop) data from new lexicons the client code isn't familiar with.
You can see these in action: https://github.com/bluesky-social/indigo/pull/870
@whyrusleeping you might want to do similar things in `gosky`.
Big picture we'll maybe want to move lexgen in this direction at some point? Relatedly, having LexiconTypeDecoder and open unions have an …
> schema-agnostic API helpers

- cmd/goat/account.go
- cmd/goat/auth.go
Supports using goat account login with [email 2fa enabled](https://github.com/bluesky-social/atproto/discussions/2435) so that users do not need to first disable 2fa to then get an email token anyways to obtain plc signing tokens.
> feat(cmd/goat): allow specifying authFactorToken

- cmd/goat/blob.go
This PR introduces the `--pds-host` argument to the `blob export` command chain.
This was needed in order to export the blobs from an old PDS when by DID document was pointing to the new one already.
> Add PDS host argument to blob export

- repomgr/repomgr.go
allows this to work on non bsky.app records
> sync get record shouldnt unmarshal

- .github/workflows/golang.yml
- bgs/bgs.go
- carstore/nonarchive.go
- cmd/beemo/Dockerfile
- cmd/bigsky/Dockerfile
- cmd/hepa/Dockerfile
- cmd/palomar/Dockerfile
- cmd/rainbow/Dockerfile
- cmd/sonar/Dockerfile
- cmd/supercollider/Dockerfile
- go.mod
This is just periodic maintenance, there isn't anything specific in 1.23 we want/need.
go v1.24 is expected in February 2025; we usually wait a month or two before upgrading (though we didn't get around to 1.23 until now).
The newer `go vet` turned up some slog syntax issues.
> bump golang version to 1.23; fix slog syntax issues

- cmd/goat/repo.go
Closes: https://github.com/bluesky-social/indigo/issues/896
Suspect repo exports to crop up in other places, but can start with this here.
> goat: longer timeout for CAR export

- cmd/goat/lexicon.go
- cmd/goat/main.go
- cmd/goat/net.go
- cmd/goat/record.go
```
goat lex resolve <nsid>           lookup a schema for an NSID
goat lex parse <path>             parse and validate Lexicon schema files
goat lex publish <path>           add schema JSON files to atproto repo
goat lex ls <nsid>                list all known Lexicon NSIDs at the same level of hierarchy
goat lex validate <uri-or-path>   validate a record, either AT-URI or local file. --catalog allows preloading a directory of lex schema files (recursively)
```
> goat: lexicon resolution helpers

- carstore/nonarchive.go
- testing/integ_test.go
this fixed like 90% of WARN messages on a narelay I was running
> narelay: drop noisy warning on no prior user data

- carstore/scylla.go
- carstore/scylla_stub.go
- cmd/bigsky/Dockerfile
- go.mod
- models/dbcid.go
importing scylla via replace doesn't work when indigo is imported as a library.
erase dependency on scylla except when building bigsky
> only depend on scylla in bigsky build

- api/agnostic/repoputRecord.go
The root issue here is "nullable and optional" not being easy to express with default golang struct marshaling. The result is this swap field getting set, but as null, which prevents actual updates (only allows creation).
This PR swaps to omitting the field. Makes it impossible to do a forced swap check of nil... but can just use create for that?
> agnostic: default putRecord to not include swapRecord field

- automod/engine/context.go
- automod/engine/engine.go
- automod/engine/ruleset.go
- automod/engine/ruletypes.go
- automod/pkg.go
- automod/rules/all.go
The idea was to integrate the automod framework with other services
which do push notifications. This never happened, and this code is
dead/untested, so removing for now.
This kind of functionality might be useful (we have lots of interaction
spam!) and could be pulled back in from git history if we ever need it.
> remove automod "notifications event" support

- automod/consumer/firehose.go
- automod/consumer/ozone.go
This didn't fix the problem we were seeing at the time, but might still be the best practice here?
> automod: give each event a separate ctx

- api/atproto/cbor_gen.go
- api/atproto/syncsubscribeRepos.go
- atproto/repo/car.go
- atproto/repo/cbor_gen.go
- atproto/repo/cmd/repo-tool/main.go
- atproto/repo/commit.go
- atproto/repo/doc.go
- atproto/repo/operation.go
- atproto/repo/repo.go
- atproto/repo/sync.go
- atproto/repo/sync_test.go
- atproto/syntax/tid.go
This is a new/alternative SDK for atproto repositories, to replace the top-level `repo` package.
It wraps the newer `atproto/repo/mst` package, and support inductive firehose.
The initial scope (eg, for this PR) is relay and consumption use-cases, not PDS and repo-maintenance use-cases (there there is some initial code supporting the later).
The earlier MST PR included a skeleton of this package; this PR fleshes it out.
Things to maybe look at before merging:
> atproto/repo: new SDK package supporting inductive firehose

- events/cbor_gen.go
- events/events.go
I'm not sure what the timeline would be on getting this deployed; we are in the middle of refactoring the relay.
On the other hand it is a pretty small/simple change.
closes: [#3086](https://github.com/bluesky-social/atproto/issues/3086)
> events: omitempty on 't' in header

- atproto/identity/base_directory.go
- atproto/identity/cache_directory.go
- atproto/identity/did.go
- atproto/identity/directory.go
- atproto/identity/handle.go
- add user-agent
- ensure we drain HTTP requests in more code paths (allows connections/streams to be re-used more efficiently)
> identity package tweaks

- automod/engine/context.go
- automod/engine/effects.go
- automod/engine/persist.go
- automod/engine/slack.go
i haven't tested this yet - and took me a little to understand what we were doing here so might still be a little off - but this should let us remove existing labels from accounts/records
> automod: add removing of labels from accounts and records

- backfill/backfill.go
Have a fair amount of random missing data coming from my consumer. Some of it i've found is that the initial repo fetch errorred for some reason and then we just drop all future events (which kinda makes sense i guess)
However its useful to distinguish why the fetch failed, distinguishing between a rate limit and 'this repo does not exist' is important for recovery situations.
> better handling of backfill errors on pds fetch

- splitter/splitter.go
I've been trying to track down an issue where in my firehose client (in Ruby) the websocket connection sometimes gets stuck, meaning that at some point events stop flowing, but the connection doesn't disconnect, so the client doesn't notice immediately that something is wrong. I've eventually added a "heartbeat" feature to my library Skyfall, where it has a timer that checks the time since the last event, and forces a reconnect if there haven't been any events for a while. This has been happening very occasionally until autumn last year, but started getting much more common since November. I worked around this by making the timer limits much lower.
But I started digging into this, and I got the feeling that the problem must be in the server's code, not on my side. I can trigger this …
> added missing connection close in splitter

- mst/diff.go
- repo/repo.go
- util/cbor.go
We already used the ipld-cbor Blockstore interface in a few places, and it's a simpler smaller interface that does all we need and isn't deprecated; spread its usage around a bit to simplify some things I was working on elsewhere in relay code
> use ipld cbor Blockstore interface

- atproto/repo/mst/node.go
- atproto/repo/mst/tree.go
- atproto/repo/repo.go
- atproto/repo/sync.go
Adds a `Walk` method to `Tree` for visiting all key/value in the MST.
Also updates `GetRecordBytes` to return the CID, along with actual bytes. It needs to be looked up from the MST anyways, and this results in one less call/lookup in some cases. Code which doesn't need the CID can just ignore that return type.
> MST walk, and repo tweak

- HACKING.md
- Makefile
- README.md
- cmd/relay/README.md
- cmd/relay/bgs/bgs.go
- cmd/relay/events/cbor_gen.go
- cmd/relay/events/consumer.go
- cmd/relay/events/events.go
- cmd/relay/events/persist.go
- cmd/relay/main.go
- cmd/relay/models/models.go
- cmd/relay/otel.go
- cmd/relay/settings.go
- removed a deadcode function
- removed lingering "bigsky" references"
- removed unused "MemPersister" (it is still in the top-level events package)
- move settings (using gorm/db) and otel code out of main.go (makes main.go shorter)
- group imports consistently
- replace some "BGS" terminology with "relay"
- update README
> relay tidy

- atproto/identity/identity.go
- atproto/syntax/handle.go
- cmd/bluepages/handlers.go
This fixes a specific typo, and also uses the declared const in more places (to avoid similar typos).
thanks @rafaelbsky for reporting!
> use syntax.HandleInvalid instead of string (fix typo)

- bgs/bgs.go
- bgs/metrics.go
- cmd/collectiondir/metrics.go
- cmd/collectiondir/serve.go
- splitter/splitter.go
- util/svcutil/metrics_middleware.go
The main motivation here is to not have `splitter` import from `bgs`; it was only doing so for MetricsMiddleware.
This moves MetricsMiddleware out to new service-oriented util package (not directly in `util/` because it depends on prometheus and echo), and updates the trivial usage to that.
Not touching `cmd/relay/` because that is getting refactored in a separate branch; and not touching `search/metrics.go` because it adds "extra" labels.
> refactor metrics middleware in to `util/svcutil`

- automod/engine/engine_ozone.go
We don't actually have any rules or behavior around this event type, just need to handle it here to reduce false-positive error logging.
Will need to be paired with an update and deploy in another internal repo, after this is merged.
> automod: have ozone engine handle newer event types

- atproto/identity/identity.go
These result in cleaner JSON for things like test fixtures. Used in new relay project.
cc: @whyrusleeping to check that other code isn't depending on the previous serialization. Eg, I think you have a memcache identity cache around somewhere. The redis caching stuff uses a different reflect-based serialization technique.
> make identity.Identity more easily JSON serializable

- go.mod
For the automatic go toolchain stuff to work, we need the full version, including patch (not just minor)
> go.mod: specify full version (1.23.0)

- cmd/rainbow/README.md
- cmd/rainbow/main.go
- splitter/firehose.go
- splitter/handlers.go
- splitter/splitter.go
- util/svcutil/logger.go
A bit of this is moving code around so I could understand which pieces were doing what. Then improved how the request proxying and requestCrawl forwarding stuff works, as part of new relay ops.
None of the core configuration or behaviors should change: I tweaked some argument names, but not the env var names, so nothing about how we deploy/operate rainbow should change.
No behavior of the core code (ringbuf, upstream websocket subscription, or serving to clients) has changed.
> rainbow: small refactors, and improve request forwarding

- .gitignore
- .golangci.yaml
- atproto/identity/apidir/apidir.go
- atproto/identity/directory.go
- atproto/lexicon/cmd/lextool/net.go
- atproto/repo/mst/mst_interop_test.go
- atproto/repo/mst/mst_test.go
- atproto/repo/mst/node.go
- atproto/repo/mst/node_insert.go
- atproto/repo/mst/node_remove.go
- atproto/repo/operation.go
- atproto/repo/operation_test.go
- atproto/syntax/did.go
- atproto/syntax/tid.go
This isn't everything, just a first pass. There were some real issues with errors not getting wired through.
I'm kind of ambivalent about the pattern:
```go
defer func() {
_ = resp.Body.Close()
}()
```
but do want to make any non-defer error returns explicit.
> batch of golangci-lint fixes in `atproto/*`

- cmd/goat/firehose.go
- cmd/goat/relay.go
- cmd/goat/relay_admin.go
- host lists and status info
- more flexible firehose-mode host parsing (wss:// vs https://)
- include blocks in `#sync` firehose output (if requested)
> more `goat relay` helpers

- atproto/identity/identity.go
This caused problems in prod. Unbeknownst to me, we had been serializing identity metadata as JSON using this struct and persisting it. Then passing back to TypeScript (not golang!), which depended on the capitalization (case-sensitive JSON parsing).
Reverting for now. Note that the go stdlib JSON code is actually case-insensitive for keys, so the text fixtures in this repo which had been updated to depend on this are not impacted (!).
Direct link to original PR: https://github.com/bluesky-social/indigo/pull/1017
> Revert "make identity.Identity more easily JSON serializable"

- cmd/sonar/sonar.go
- go.mod
Fine to use this elsewhere for perf, but let's get it out of this dependency tree.
(note: this is not actually related to recent serialization bug, just cleaning this up)
> sonar: just use stdlib json (removing go-json dependency)

- cmd/relay/handlers.go
- cmd/relay/main.go
- cmd/relay/relay/account.go
- cmd/relay/relay/crawl.go
- cmd/relay/relay/domain_ban.go
- cmd/relay/relay/host.go
- cmd/relay/relay/ingest.go
- cmd/relay/relay/relay.go
- cmd/relay/testing/runner.go
This involved both adding `.WithContext(ctx)` to any database calls, and wiring through `ctx` in a couple functions which should have had it already.
The one place I didn't wire this through is gorm auto database migrations in the setup command. It felt less necessary during process initialization, though I can add if requested.
> wire through ctx for all database (gorm) operations

- splitter/handlers.go
- splitter/splitter.go
Rainbow was accidentially following HTTP redirects and streaming back full CAR files when handling getRepo requests.
This correctly passes through the HTTP 3xx response back to the client, which then does the request to the PDS.
Note that proxying or returning the CAR directly isn't *forbidden*, it just isn't the behavior we want right now. We might eventually do proxying and coalescing/caching in rainbow/relay to reduce network load.
> rainbow: fix getRepo redirects

- cmd/relay/main.go
- cmd/relay/pull.go
This helper command queries an existing relay instance for known hosts, and adds them to the local instance (if they aren't already). The intention is to make bootstrapping a new full-network relay easier (eg, avoid wrangling bash script pipelines and admin API requests).
It does some filtering and checks to try and skip inactive/stale hosts: only "active" (or "idle") hosts which have seen at least one event remotely (aka, `seq` is positive), and does an (optional) HTTP request to `describeServer` on the host to check it is live.
This command should only be run if the overall relay isn't already running as a daemon. It is safe to run it multiple times, or after the relay has been running for some time.
(this code is pretty off-the-cuff; I've run it a few times to test, and it isn't …
> relay pull-hosts command (for public bootstrapping)

- cmd/relay/main.go
- cmd/relay/service.go
- relay support for multiple admin passwords at the same time (to make secret rotation easier)
- have a parallel PR going with README updates; will mention in that PR that the env var is comma-separated, so passwords can't contain a comma
- does not change the arg name or env var name, so existing configs work fine
- also switches to constant-time string comparison using go stdlib (more secure)
> support multiple admin passwords

- Makefile
- cmd/goat/relay.go
little helper for comparing the host lists of two distinct relay instances.
sequences are always counting up, and won't be exact matches! this implementation allows "slop" between the sequences.
an alternative implementation would be do do multiple interleaved enumeration requests for each relay, then see if there is overlap between the ranges; if there is overlap, presumably they are both relatively in sync.
> goat relay host diff

- cmd/relay/relay/host.go
Minor changes: 
1. Removes duplicate WithContext() call
2. Uses `First()` instead of `Find()` where only one struct is expected
> Small cleanup for relay host code

- cmd/relay/stream/eventmgr/event_manager.go
- events/events.go
The issue here is that when a cursor is supplied, sub.output isn't actually the channel which is passed along to calling code; the 'out' chan is what gets returned.
This means that sub.output getting closed needs to be wired through to 'out' getting closed as well.
NOTE: this is in old relay code ("BGS"). If we like this fix, should copy it to new relay code (`indigo:cmd/relay/stream`) before merging.
> bgs: ensure output channel is closed if it isn't sub.output

- cmd/relay/testing/consumer.go
Trying to reduce the frequency of flakey test failures in github actions CI. Suspect this is due to over-utilized test runners.
This should not impact "happy path" (tests passing), but makes working on the tests a bit annoying. Might be possible to check env vars to see if the test is running in CI and have a different timeout for that situation.
> bump relay integration test timeout from 3s to 10s

- cmd/goat/blob.go
Prints the error and continues rather than bailing entirely during blob export. Slightly worse in the "i have a connection problem" scenario, but means repository exports where some blobs are missing actually work now rather than getting stuck.
Was trying to migrate my main to my own PDS and ran into it, and figured addressing it would be both simple enough and useful to others trying to do the same.
> Changed error handling during blob export command in goat to help with account migration

- LICENSE-DUAL
- README.md
I had this wrong previously; the formal company name does include "Social".
> use legally registered name for company

- cmd/lexgen/main.go
- lex/gen.go
`cmd/lexgen` is unprepared for a world where it's not generating schemas for everything in `atproto`! Both type generation and server stub generation generate types/stubs for every specified lexicon; this causes generated code to be somewhere between "challenging" and "unusable" for external projects — we'd prefer to have codegen that creates types for our Go program while still being able to externally reference `com.atproto` and `app.bsky` schema
This change introduces an `--external-lexicons` flag that can take multiple directories. It functions the same way as the positional lexicon arguments, those lexicons are all loaded into the code and can be referenced, but their types/stubs are not  included as part of the generated output. This yields the following command for Streamplace; …
> lexgen: add --external-lexicons

- atproto/crypto/keys.go
- atproto/crypto/keys_test.go
Pretty simple one: actually add `Multibase()` output encoding to `PrivateKeyExportable` interface, as foreshadowed by an earlier comment.
Adds a round-trip test for the two current curve types supported.
> crypto: add Multibase() method to PrivateKeyExportable interface

- cmd/relay/handlers.go
`handleComAtprotoSyncRequestCrawl` should pass its boolean `admin` flag to `SubscribeToHost`, to let it bypass the daily new host limit when run as admin. Currently it just always passes `false`. The result is that when calling `goat relay admin host add` or the `/admin/pds/requestCrawl` endpoint, you get a "500 new host subscriptions temporarily disabled" error in response.
> bypass subscribe limits in /admin/pds/requestCrawl

- atproto/crypto/jwk.go
- atproto/crypto/jwk_test.go
- atproto/crypto/keys.go
Basic JWK serialization of the curves we use for atproto crypto (P-256, K-256), for public keys only. This will get used in OAuth implementation.
The decision to implement this directly instead of using something like https://github.com/lestrrat-go/jwx is entangled with deciding to use `golang-jwt` for service auth implementation (which is distinct from OAuth implementation, and doesn't directly require JWKs). I think the secp256k1 experimental support in `jwx/jwt` would pull in a new dependency/implementation, and I like our current choice, and it doesn't seem as easy to wedge in a new curve type/implementation with `jwx` family of packages.
On the other hand, I sure don't love parsing those uncompressed bytes out in to `(x, y)` coordinates!
I thought about only exposing `[]byte` JSON …
> basic JWK support in crypto SDK

- bgs/fedmgr.go
- cmd/gosky/debug.go
- cmd/gosky/main.go
- cmd/gosky/streamdiff.go
- cmd/sonar/sonar.go
- cmd/supercollider/main.go
- events/diskpersist/diskpersist.go
- events/persist.go
- pds/server.go
- search/firehose.go
- testing/utils.go
This was an old branch. which I have now rebased on top of https://github.com/bluesky-social/indigo/pull/1082 (which got merged to main).
It now basically just adds `#sync` support in a few more places it was missing.
> sync v1.1 event updates: add `#sync`, remove `#handle`, `#migrate`, `#tombstone`

- atproto/auth/http_test.go
- atproto/auth/jwt_test.go
- atproto/client/password_auth_test.go
- atproto/identity/cache_directory.go
- atproto/identity/identity.go
- atproto/identity/redisdir/redis_directory.go
Making a couple internal methods and types private, and gave a couple sub-types better names.
These are technically API breaking changes, but i'm pretty confident the internal bits are not being used outside this repo. And the renames should also not be particularly disruptive (if at all), and best done sooner than later (eg, before more folks start building on this API surface).
> identity SDK tweaks

- atproto/identity/apidir/apidir.go
- atproto/identity/base_directory.go
- atproto/identity/cache_directory.go
- atproto/identity/handle.go
- atproto/identity/identity.go
- atproto/identity/identity_test.go
- atproto/identity/mock_directory.go
- atproto/identity/mock_directory_test.go
- atproto/identity/redisdir/redis_directory.go
- cmd/bluepages/handlers.go
- tries harder to find a valid handle in alsoKnownAs list (doesn't stop at the first `at://` if it was not a valid handle)
- normalizes handles when extracting from DID docs / identities
- ensures that bi-directional handle comparisons are done with normalized handles
- ensures that caching is done with normalized version of handles
- adds some tests for all this
> identity SDK: match spec better w/r/t handle normalization and extraction from DID doc alsoKnownAs

- .github/workflows/golang.yml
- cmd/beemo/Dockerfile
- cmd/bigsky/Dockerfile
- cmd/bluepages/Dockerfile
- cmd/collectiondir/Dockerfile
- cmd/goat/util.go
- cmd/hepa/Dockerfile
- cmd/palomar/Dockerfile
- cmd/rainbow/Dockerfile
- cmd/relay/Dockerfile
- cmd/sonar/Dockerfile
- cmd/supercollider/Dockerfile
- go.mod
- mst/mst_test.go
Don't have any specific burning need for this, just keeping up with releases.
Go 1.25 is expected in August; we'll probably wait until at least v1.25.1 and an Alpine release to upgrade.
> bump to go v1.24

- lex/type_schema.go
This fixes lexgen for empty unions (which it now treats similarly to `unknown`).
Also handles the special "meta" unknown field in `tools.ozone.moderation.defs#modTool`, which is a "true" unknown (aka, it will not have `$type`, similar to plc ops and did docs).
I tested running against atproto main, and the API part worked, but current lexgen adds yet more params to queryEvents which breaks things.
> lexgen empty union

- atproto/identity/mock_directory.go
I've wanted this when writing tests that use the mock directory from multiple goroutines.
> Make MockDirectory Thread Safe

- cmd/goat/account_plc.go
- cmd/goat/plc.go
Addresses #1128 and also adds some "hints" to error messages regarding when to use `goat plc` vs `goat account plc`. There's perhaps still room for improvement on the command help texts though.
Note: I haven't fully tested a PLC update via `goat account plc submit` with these changes, yet
> goat: improve PLC-related error messages

- cmd/relay/handlers.go
this change just makes sure `repo` is not nil before we try to pull a `Rev` out of it.
assigning the Rev from the repo follows what's *almost* a boilerplate golang error handler, but is sneakily not handling `relay.ErrAccountRepoNotFound` -- seems the intent is to provide a happy-path response for a common error case.
unfortunately the Rev assignment tried to dereference that from `repo` unconditionally, so it panicked in the allowed-error path.
(still need to test and will verify on my relays)
> fix nil pointer deref for ErrAccountRepoNotFound

- atproto/auth/oauth/oauth.go
I believe that we need to set the accountDID to ident.DID so we can set info.DID later on if we are not given an auth server url
> set account did if ident

- atproto/auth/oauth/oauth.go
- atproto/auth/oauth/types.go
This is a breaking change, and could impact database schemas or even stored data for already-deployed code relying on this package.
On the other hand, it makes things consistent, and I think easier to work with.
I'll try to do a quick scan for projects already building on this (new) package.
> oauth: store auth req scopes same way as auth session (array of strings)

- atproto/auth/oauth/oauth.go
- atproto/auth/oauth/types.go
Addresses #1152
This can be tested by initiating a login with the demo client app, but hitting "cancel" on the AS login page (or by refusing to grant the requested scopes).
> OAuth client: Surface callback error responses

- atproto/auth/oauth/oauth.go
According to [rfc7523](https://datatracker.ietf.org/doc/html/rfc7523#page-6) a client assertion jwt MUST have an exp ( expiresat ) claim. This could also be a issue with the assertion verification in the reference PDS code ( seems to accepts assertions without the exp claim)  and [python-oauth-web-app](https://github.com/bluesky-social/cookbook/tree/main/python-oauth-web-app) not sending the exp claim either
> Client assertion jwt missing exp ( expiresat ) claim

- atproto/auth/oauth/cmd/oauth-web-demo/main.go
- atproto/auth/oauth/doc.go
- atproto/auth/oauth/oauth.go
- atproto/auth/oauth/session.go
- atproto/auth/oauth/types.go
Addresses #1135
Revocation has similar properties to session refresh, so I implemented it in `ClientSession` alongside `RefreshTokens`.
A high-level `Logout` helper has been added to `ClientApp` which both revokes the tokens against the AS and deletes the session from the app's session store.
Due to aforementioned similarity between refresh and revocation, I created the `ClientSession.postToAuthServer` helper to reduce duplicated logic. (Note that "DPoP retry" logic is still duplicated elsewhere, I couldn't think of any elegant way to eliminate it)
> OAuth client SDK: Support token revocation via Logout helper
