.gitignore, Makefile, bgs/bgs.go, carstore/repo_test.go, cmd/bigsky/main.go, cmd/gosky/main.go, cmd/pds/main.go, indexer/posts_test.go, pds/auth.go, pds/fedmgr.go, pds/feedgen.go, pds/handlers.go, pds/keygen_test.go, pds/server.go, pds/stubs.go, repomgr/ingest_test.go, repomgr/repomgr.go, testing/utils.go, testscripts/cleanup.sh
Not everything we discussed this morning, but some.
Note that the data directories and file names changed, so your local setup might need to be wiped. The commands do (naively) try to create any missing directories when starting up.
My intention is to just merge this to main in few minutes after giving @whyrusleeping a heads up.
=> small early refactors

.github/workflows/container-bigsky-ghcr.yaml, cmd/bigsky/Dockerfile
- dockerfile
- github action to build and upload container
=> bigsky deployment infra

bgs/bgs.go, pds/server.go
These do a trivial connection to database to ensure things are actually running.
=> add /xrpc/_health checks to bigsky and pds

cmd/bigsky/README.md
These are basically dupe of the docs in our internal infra, but want some basic info here as well as there.
=> bigsky: start of a deployment/env README

go.mod, go.sum
These are @whyrusleeping's commits, just pulled them out in to a separate PR for faster merging.
=> just update did:web library

api/extra.go
Inspired by https://github.com/bluesky-social/indigo/pull/49
We also change the semantics of how the PDS is specified
=> Get service from PLC using new did doc semantics

cmd/beemo/main.go
What it says! Pretty small formatting change.
=> beemo: improve slack message formatting

bgs/bgs.go, bgs/fedmgr.go, bgs/handlers.go, carstore/bs.go, events/dbpersist.go, models/models.go, repomgr/repomgr.go, testing/utils.go
This is a bit of a grab bag right now since my last PR got merged too early and was also rebased, which made rebasing this one an experience.
=> Fixup event ops PR

carstore/bs.go
This goes from 59 bytes per cid in the db to 36, a pretty hefty savings.
=> use dbcid type for carstore cid references

bgs/bgs.go, carstore/bs.go, cmd/bigsky/main.go, cmd/stress/main.go, events/cbor_gen.go, events/dbpersist.go, events/events.go, util/dbcid.go
We don't have a lexicon for this yet, but this does prevent things from breaking outright for now.
=> add 'too big' event flag to events

HACKING.md, cmd/labelmaker/README.md, cmd/labelmaker/example_keywords.json, cmd/labelmaker/main.go, cmd/labelmaker/sqrl_example/bsky/cryptocurrency_keywords.txt, cmd/labelmaker/sqrl_example/bsky/main.sqrl, cmd/labelmaker/sqrl_example/bsky/post.sqrl, cmd/labelmaker/sqrl_example/bsky/profile.sqrl, labeling/hiveai.go, labeling/hiveai_test.go, labeling/keyword_labeler.go, labeling/keyword_labeler_test.go, labeling/micro_nsfw_img.go, labeling/service.go, labeling/sqrl.go, labeling/test_files/hiveai_resp_example.json, labeling/util.go, labeling/util_test.go, labeling/xrpc_handlers.go
Making calls out to APIs to help with labeling determinations.
This round of work will include a basic (not production ready) NSFW image filter, and SQRL API. Everything is still single-threaded, not concurrent.
=> labelmaker: external API calls

cmd/beemo/main.go, cmd/bigsky/main.go, cmd/fakermaker/main.go, cmd/gosky/main.go, cmd/labelmaker/main.go, cmd/laputa/main.go, cmd/stress/main.go
=> get GOLOG_LOG_LEVEL working with dotenv

.gitignore, Makefile
I'll probably just self-approve these in the next few days.
=> couple trivial dev tweaks

lex/util/lex_test.go, lex/util/lex_types.go
Hopefully fixes https://github.com/bluesky-social/indigo/issues/103
Thanks to @mattn for surfacing this post-lex-refactor, via his `bsky` CLI tool
=> hotfix: blob marshal/unmarshal

cmd/gosky/main.go
=> fix gosky vote command

cmd/beemo/Dockerfile, cmd/labelmaker/Dockerfile, example.dev.env
Might even skip review on these
=> quick dev fixes

api/atproto/admindefs.go, api/atproto/admindisableInviteCodes.go, api/atproto/admingetInviteCodes.go, api/atproto/adminsearchRepos.go, api/atproto/admintakeModerationAction.go, api/atproto/labeldefs.go, api/atproto/labelqueryLabels.go, api/atproto/labelsubscribeLabels.go, api/atproto/repolistRecords.go, api/atproto/repostrongRef.go, api/atproto/servercreateInviteCode.go, api/atproto/servercreateInviteCodes.go, api/atproto/servercreateSession.go, api/atproto/serverdefs.go, api/atproto/servergetAccountInviteCodes.go, api/atproto/servergetSession.go, api/atproto/synclistRepos.go, api/bsky/actordefs.go, api/bsky/feeddefs.go, api/bsky/notificationlistNotifications.go, bgs/handlers.go, bgs/stubs.go, cmd/beemo/main.go, cmd/gosky/main.go, fakedata/accounts.go, lex/gen.go, pds/handlers.go, pds/handlers_test.go, pds/stubs.go, repomgr/ingest_test.go
I'm not using the lexgen stuff because the auth is different for this route. Not quite sure how to properly deal with that yet so i'm yoloing a one-off http request
=> add helper command for generating invite codes

api/plc.go, bgs/bgs.go, bgs/fedmgr.go, cmd/bigsky/main.go, events/consumer.go, events/events.go, indexer/indexer.go, models/models.go, pds/handlers.go, pds/server.go, plc/fakedid.go, plc/plc.go, testing/integ_test.go, testing/utils.go
basic handling for handle updates and pds migrations.
Theres likely more cases to be handled (migrateTo can be nil, what does that imply?) but this should be an improvement for now.
=> handle updates and pds migrations

.gitignore
Maybe other people are more diligent than me but I almost committed them with my first code exploration.
=> gitignore default creds

bgs/bgs.go, cmd/gosky/debug.go, cmd/gosky/main.go, events/dbpersist.go, events/repostream.go, indexer/crawler.go, indexer/indexer.go, lex/util/lex_types.go, repomgr/repomgr.go, xrpc/xrpc.go
And some other misc improvements.
=> Improve handling of bad records

cmd/gosky/admin.go, cmd/gosky/main.go
Some utilities to help us audit how we are giving invites out
=> add command for listing invite tree and checking user invites

api/atproto/syncsubscribeRepos.go, api/bsky/embedrecord.go, lex/gen.go
This way we can run "make lexgen" and not have to manually tweak the output.
=> lex: regenerate APIs, moving manual hacks into code generator

mst/mst_util.go
isValidMstKey used regexp, which isn't super fast in Go. Write it out by hand instead, making it much faster:
│    before    │                after                │
│    sec/op    │   sec/op     vs base                │
IsValidMstKey-8   276.15n ± 1%   27.49n ± 4%  -90.05% (p=0.000 n=10)
Also, allocate less in deserializeNodeData, reusing a scratch buffer between entries and only doing the []byte to string conversion once.
=> mst: optimize deserializeNodeData allocs, isValidMstKey CPU

mst/mst_test.go
To establish a baseline for future DiffTrees optimizations.
=> mst: add BenchmarkDiffTrees

search/handlers.go, search/query.go, search/server.go
Not sure why ive been dragging my feet on this but this should make search suck less
=> add sorting and pagination and 'and' to search

events/events.go, events/parallel.go
Havent integrated this yet, but I figured it would be good to send up for a review.
Pretty straightforward to make this generic so we can use it for labels when we need to as well.
=> Add a concurrent event processor helper

bgs/bgs.go, carstore/bs.go, events/dbpersist.go, events/events.go, events/persist.go, indexer/crawler.go, indexer/indexer.go, pds/handlers.go, repo/repo.go, repomgr/repomgr.go, testing/integ_test.go, testing/utils.go
I still want to add more tests to this, but this is done enough to start in on some code review.
=> add support for handling rebase events

cmd/gosky/debug.go
Some basic checks to help find issues with feed generator deployments
=> add command to help debug feed generators

bgs/fedmgr.go, cmd/gosky/debug.go, cmd/gosky/main.go, cmd/gosky/streamdiff.go, events/consumer.go, events/parallel.go, events/repostream.go, search/server.go, testing/labelmaker_fakedata_test.go, testing/utils.go
Add an easy way to process the event stream in parallel
=> integrate consumer pool into stream handler

events/dbpersist.go
This is based on the rebase PR since they would conflict otherwise.
=> Fewer database operations for event persistence

cmd/gosky/main.go
allow did resolve to just print the handle, allow handing out invites to a did
=> some tweaks to gosky commands

bgs/admin.go, bgs/bgs.go, bgs/fedmgr.go, bgs/handlers.go, carstore/bs.go, cmd/bigsky/main.go, events/consumer.go, indexer/indexer.go, models/models.go, repomgr/repomgr.go, util/http.go, xrpc/xrpc.go
Until we get a proper 'bootstrap sync' protocol, im adding an env var to allow us to skip ratelimiting on the pds.
also cleaned up the handling of too-big events a bit
=> misc tweaks made for rerunning bgs scrape

bgs/bgs.go, bgs/handlers.go, models/models.go, testing/integ_test.go, testing/utils.go
Add the ability to ban domains and subdomains from being scraped by the bgs
=> add ability to ban entire domains, including subdomains

carstore/bs.go
The GORM create helpers dont have any way to avoid 'returning' the ID values of created records, and that was causing a noticeable performance hit in this critical section.
=> optimize block_ref creation

bgs/bgs.go, cmd/gosky/debug.go, cmd/gosky/main.go
A number of logging improvements, some cli tooling changes
=> misc improvements for bgs operation

cmd/gosky/admin.go
=> allow admin checkUser to accept a did

bgs/admin.go, bgs/bgs.go, ts/bgs-dash/src/App.tsx, ts/bgs-dash/src/components/Dash/Dash.tsx, ts/bgs-dash/src/components/Domains/ConfirmDomainBanModal.tsx, ts/bgs-dash/src/components/Domains/Domains.tsx, ts/bgs-dash/src/components/Repos/ConfirmRepoTakedownModal.tsx, ts/bgs-dash/src/components/Repos/Repos.tsx
=> Handle repo takedowns, make admin dash a bit more mobile friendly

bgs/bgs.go, bgs/metrics.go, carstore/bs.go, events/dbpersist.go
DB utilization gets really high for some reason if we're not paginating the playback and have a lot of events to playback. This _might_ help?
=> Add pagination to DBPlayback and some metrics

cmd/bigsky/main.go, events/dbpersist.go, events/dbpersist_test.go, events/diskpersist.go, events/diskpersist_test.go, events/events.go, events/persist.go, events/yolopersist.go, models/uid.go, repomgr/bench_test.go, testing/utils.go
Still need to implement some of the trickier parts like takedowns and rebases, but the primary IO flows are here.
=> disk based event persistence

cmd/fakermaker/README.md, cmd/fakermaker/main.go, fakedata/generators.go, testing/pds_fakedata_test.go
This gets the tool working with, eg, sandbox, or staging.
Tested with a small handful of domains.
=> fakermaker: add support for invite code and domain suffix

cmd/gosky/admin.go
- Adds a flag to the `listInviteTree` to revoke an account's existing invites
=> Add flag to revoke existing invites

cmd/beemo/Dockerfile, cmd/bigsky/Dockerfile, cmd/labelmaker/Dockerfile, cmd/palomar/Dockerfile
Might as well, as we are doing the golang v1.21 change
=> dockerfile: update to alpine 3.18

cmd/bigsky/main.go
Use the `rlbypass` header for handle resolution when resolving against `.bsky.social` handles.
=> Support rlbypass for handle resolution

LICENSE.md, README.md
=> update Bluesky PBLLC to PBC (Public Benefit Corporation)

bgs/bgs.go
This change updates the handle change codepath to make sure both ActorInfos and the Users tables reflect the new handle appropriately. There were issues with handle changes getting lost or taking multiple tries to apply but this seems to have worked those issues out.
=> Resolve Handle Change Propagation in BGS

bgs/bgs.go, bgs/metrics.go, indexer/crawler.go, indexer/indexer.go, indexer/metrics.go, repomgr/metrics.go, repomgr/repomgr.go, search/firehose.go, search/indexing.go, search/metrics.go, search/parse_query.go, search/server.go, testing/integ_test.go
Adding some more visibility to BGS crawler state so we can see how aggressively it's crawling.
I also aded a few more "verbose" comments because the state machine in the crawler `mainLoop` is a bit cryptic to reason about without reading the entire thing very thoroughly.
=> Metrics tracking indexer and crawl stats plus prepping for search metrics

cmd/bigsky/main.go, repomgr/repomgr.go
Im not confident this is right yet, but giving it a try to see if it fixes our issues
=> processRepo callback needs deltastore bs for gap fill

cmd/gosky/admin.go
- Modifies`takeDownAccountCmd` to take multiple dids for bulk takedowns 
- Renames cli command `takeDownAccount` to standardize with other commands
Example command:
`./gosky admin take-down --reason="<reason here>" --admin-user="<did here>" --revert-actions exampleuser.bsky.social exampleuser2.bsky.social`
=> Allow bulk dids for takedown

cmd/gosky/car.go, cmd/gosky/main.go, repo/repo.go
```
$ ./gosky sync downloadRepo atproto.com
$ ./gosky car unpack "did:plc:ewvi7nxzyoun6zhxrhs64oiz.car"
$ ./gosky car unpack --cbor "did:plc:ewvi7nxzyoun6zhxrhs64oiz.car"
$ tree "did:plc:ewvi7nxzyoun6zhxrhs64oiz" | head
did:plc:ewvi7nxzyoun6zhxrhs64oiz
├── app.bsky.actor.profile
│   ├── self.cbor
│   └── self.json
├── app.bsky.feed.like
│   ├── 3jucagnrmn22x.cbor
│   ├── 3jucagnrmn22x.json
│   ├── 3jucahkymkk2e.cbor
│   ├── 3jucahkymkk2e.json
│   ├── 3jucaj3qgmk2h.cbor
[...]
```
=> gosky commands to download repo CAR file, and unpack into JSON/CBOR files in directory structure

HACKING.md, README.md, cmd/beemo/README.md
Doing a pass over all our git repos.
rendered: https://github.com/bluesky-social/indigo/blob/bnewbold/readme-tweaks/README.md
=> update READMEs and dev docs

search/indexing.go
Handle failed DID lookups that don't return errors properly
=> Fix nil identity null pointer

carstore/bs.go, cmd/bigsky/main.go, repomgr/bench_test.go
who thought 1000 was a good enough number??
=> make the did cache not tiny

pds/server.go, testing/integ_test.go
quick test to make sure empty events get handled properly
=> test that empty events make it through

cmd/gosky/debug.go
calling getRepo against bsky.social for an account thats been migrated no longer works, so this makes the command "do what i mean" more
=> auto detect correct pds for 'home' server in compare repos

api/atproto/admindefs.go, api/atproto/admindisableAccountInvites.go, api/atproto/adminenableAccountInvites.go, api/atproto/admingetModerationReports.go, api/atproto/admintakeModerationAction.go, api/atproto/labeldefs.go, api/atproto/labelqueryLabels.go, api/atproto/repoapplyWrites.go, api/atproto/repocreateRecord.go, api/atproto/repodeleteRecord.go, api/atproto/repolistRecords.go, api/atproto/repoputRecord.go, api/atproto/synclistBlobs.go, api/atproto/syncsubscribeRepos.go, api/bsky/actordefs.go, api/bsky/actorsearchActors.go, api/bsky/actorsearchActorsTypeahead.go, api/bsky/feedsearchPosts.go, api/bsky/unspeccedsearchActorsSkeleton.go, api/bsky/unspeccedsearchPostsSkeleton.go
This is pretty no-op, just pushing it through ahead of some other lexgen changes.
- retains commented-out didDoc fields
- does not include new threadgate Lexicon (lexgen issues on some of this?)
=> partial lexgen (just comments)

automod/slack.go, cmd/hepa/server.go
didn't want to clutter other PRs with these
=> automod: small fixes

atproto/crypto/cmd/atp-crypto/main.go, atproto/crypto/keys.go, atproto/identity/cmd/atp-id/main.go, atproto/identity/did.go, atproto/syntax/cmd/atp-syntax/main.go, cmd/gosky/account.go, cmd/gosky/admin.go, cmd/gosky/bgs.go, cmd/gosky/debug.go
I only recently discovered the `ArgsUsage` field in urfave/cli command config. It helps a lot!
=> CLI usage improvements, and crypto private key gen helper

cmd/hepa/main.go, cmd/hepa/server.go
Was debugging an un-related issue and the current messages are unhelpful, so added a bunch.
=> hepa: more descriptive process startup error messages

atproto/crypto/keys.go, atproto/identity/identity.go, atproto/syntax/datetime.go, atproto/syntax/uri.go, bgs/bgs.go, carstore/bs.go, carstore/repo_test.go, cmd/fakermaker/README.md, cmd/labelmaker/README.md, cmd/palomar/README.md, events/diskpersist.go, fakedata/generators.go, indexer/indexer.go, mst/mst_util.go, pds/server.go, testing/integ_test.go
Hadn't run one of these in a while.
=> quick codespell pass over entire repo

automod/event.go
This is pretty trivial, i'll probably just self-merge.
=> automod: actually return error (bugfix)

cmd/gosky/main.go, events/dbpersist.go, events/diskpersist.go, go.mod, go.sum, mst/mst_test.go, plc/caching.go, util/cliutil/util.go
(see commit messages - please do not squash)
=> remove three unnecessary direct dependencies

automod/rules/gtube.go, automod/rules/hashtags.go, automod/rules/identity.go, automod/rules/interaction.go, automod/rules/keyword.go, automod/rules/misleading.go, automod/rules/private.go, automod/rules/profile.go, automod/rules/promo.go, automod/rules/replies.go
As discussed; pretty straight-forward
=> automod: annotate rules with function types

automod/engine/effects.go
After discussion with mod team.
cc: @warpfork for visibility, but i'm going to self-merge this as it is mostly a policy/process tweak, not a code thing
=> automod: change report fresh/limit period to one day

automod/README.md, automod/cachestore/doc.go, automod/capture/doc.go, automod/countstore/doc.go, automod/doc.go, automod/engine/doc.go, automod/engine/fetchaccountmeta.go, automod/engine/ruleset.go, automod/flagstore/doc.go, automod/rules/doc.go, automod/setstore/doc.go
=> automod: a bit more docs/comments

cmd/hepa/consumer.go, cmd/hepa/main.go
process record updates (in addition to creates), eg for profile records.
also make log level configurable via an env var (or CLI arg).
=> hepa: small improvements

automod/engine/effects.go, automod/engine/engine.go, automod/rules/hashtags.go, automod/rules/keyword.go, automod/rules/replies.go
branch collecting tweaks that have been temporarily deployed in prod
=> automod polish

automod/engine/persist.go, automod/engine/persisthelpers.go
The place this comes up most often is profile records, which are updated frequently. For post records, the updates (re-reporting, etc) aren't a big deal yet.
=> automod: de-dupe labels, flags, reports on records (eg, profiles)

search/parse_query.go
Addresses https://github.com/bluesky-social/indigo/issues/578
=> Parse queries better for search

automod/rules/helpers.go, automod/rules/interaction.go, automod/rules/mentions.go, automod/rules/promo.go, automod/rules/replies.go
=> automod interaction rule tweaks (anti-spam)

bgs/fedmgr.go, cmd/hepa/consumer.go, events/consumer.go
These weren't getting routed through
=> process identity events from the pds slurper

cmd/gosky/main.go
got tired of translating bsky.app links into at:// links
=> handle bsky.app urls in get-record

automod/visual/hiveai_client.go
Experimental improvement to auto-labeling, specifically for furry art (aka, cartoon content). Should reduce false-positive sexual and porn labels on this category of content (though still some false-positives).
=> visual: tweak Hive thesholds for furry content specifically

backfill/gormstore.go
=> Only use INDEXED BY in queries when the driver is a sqlite3 driver

indexer/repofetch.go
If we have a filesystem messup for some reason just wipe and reset the repo
=> fallback to clean repo reset in more cases

automod/rules/all.go, automod/rules/reposts.go
TODO:
This PR adds basic checks for relatively new accounts reposting too frequently and reports them to ozone.
=> automod: add basic repost rule

api/bsky/cbor_gen.go, go.mod, go.sum
use its improved handling of a []*string field
=> upgrade cbor-gen

carstore/bs.go
We need to find a good way to run these tests on postgres
=> in postgres use optimized where in query

automod/visual/hiveai_client.go, automod/visual/hiveai_rule.go, automod/visual/prescreen.go, cmd/hepa/main.go, cmd/hepa/server.go
for now, just going to log if the pre-screen fails at its job
=> add rigging for hive to pre-screen images before sending to hive

automod/rules/helpers.go, automod/rules/helpers_test.go
couple of helpers for a case i keep running into.
=> add `PostParentOrRootIsDid` and `PostMentionsDid` to automod helpers

automod/capture/testing.go, automod/consumer/firehose.go, automod/engine/engine.go, automod/engine/ruleset.go, automod/engine/ruletypes.go
@foysalit: this is pulling out some of the engine-layer refactors from https://github.com/bluesky-social/indigo/pull/708
=> automod: refactor identity and account event processing

cmd/bigsky/main.go
This is mostly driven by feedback from folks running indie relays.
=> relay: env var for persist dir, and alt env var for data dir

api/atproto/cbor_gen.go, api/bsky/cbor_gen.go, api/cbor_gen.go, api/chat/cbor_gen.go, atproto/data/cbor_gen.go, events/cbor_gen.go, go.mod, go.sum, lex/util/cbor_gen.go, lex/util/cbor_gen_test.go, mst/cbor_gen.go, repo/cbor_gen.go, util/labels/cbor_gen.go
This should help memory pressure on all firehose consumers, but especially on the relay
=> update to more optimized cborgen

bgs/bgs.go, bgs/compactor.go, bgs/handlers.go
should cut ~3% of all DB usage on the prod relay
=> add a user cache on the bgs

cmd/bigsky/main.go, go.mod, go.sum, plc/memcached.go
tired of waiting for the did cache to warm up when relay restarts? wait no longer! put the cache in memcached (still also have local in-process cache, but backed by "L2" cache in memcached)
=> add memcached for did cache to relay

cmd/bigsky/copy_pdses.py, cmd/bigsky/resync_pdses.py
copy_pdses.py will /admin/pds/list at one relay and requestCrawl, changeLimits, block, and unblock as needed on the dest relay 
resync_pdses.py takes a list of hosts and either /admin/pds/resync them or requestCrawl & changeLimits them
=> tool for relay pds resync, and copy pds state from one relay to another

atproto/data/data.go, automod/engine/slack.go, automod/flagstore/flagstore_mem.go, automod/helpers/bsky.go, automod/rules/harassment.go, automod/rules/nostr.go, automod/rules/promo.go, automod/rules/quick.go, cmd/astrolabe/handlers.go, cmd/netsync/main.go, cmd/sonar/main.go, fakedata/accounts.go, lex/type_schema.go, repomgr/ingest_test.go, search/handlers.go, search/transform.go
- fix staticcheck SA2000
- fix staticcheck S1011
- fix unnecssary fmt.Sprintf (staticcheck S1039)
=> Fix staticcheck SA2000, S1011 and S1039

cmd/bigsky/main.go, cmd/gosky/main.go, util/cliutil/ipfslog.go, util/cliutil/util.go
add integration into main()s for slog, set level, output file, log rotation rules, text or json
also connect to ipfs log used by some dependencies.
=> slog setup util for indigo main() functions

bgs/admin.go, bgs/fedmgr.go
when we /admin/pds/block a PDS, also try to disconnect from it at that time
=> disconnect a pds when we block it

bgs/admin.go, bgs/fedmgr.go, bgs/handlers.go, carstore/README.md, carstore/bs.go, carstore/last_shard_cache.go, carstore/nonarchive.go, carstore/repo_test.go, carstore/scylla.go, carstore/sqlite_store.go, cmd/bigsky/main.go, cmd/gosky/debug.go, go.mod, go.sum, indexer/crawler.go, indexer/indexer.go, indexer/repofetch.go, models/dbcid.go, repo/repo.go, repomgr/repomgr.go, testing/utils.go
also toy sqlite blockstore
this is a squash-rebase of #882
=> scylla blockstore

repo/repo.go
I had these in my local working tree; @brianolson also added some error messages in between. I think mine might be clearer?
=> improve some repo error messages

api/atproto/synclistReposByCollection.go, api/bsky/actordefs.go, api/bsky/feedpostgate.go, api/bsky/feedthreadgate.go
mostly wanted to ensure the collectiondir lexicon was synchronized (it already was, only diff was a comment).
also pulled in recent threadgate changes for app.bsky.
there were also ozone changes, but those are disruptive to update code, so not biting that off here (sorry!).
=> small/partial lexgen (2025-02-17)

cmd/goat/account_plc.go, cmd/goat/crypto.go, cmd/goat/key.go, cmd/goat/main.go, cmd/goat/plc.go
eg:
```sh
goat key generate
goat account login -u $HANDLE -p $PASSWORD
goat account plc current
goat account plc request-token
goat account plc add-rotation-key --token $PLCTOKEN $PUBKEY
goat account plc current
```
=> goat: basic account PLC key commands

backfill/gormstore.go
=> actually update revs in gormstore

cmd/sonar/main.go, cmd/sonar/metrics.go, cmd/sonar/sonar.go
trying to tidy up the large number of top-level directories.
don't have super strong feelings on this if you think it should stay as-is.
=> move all sonar code in to ./cmd/sonar/

api/atproto/cbor_gen.go, events/consumer.go, events/events.go, gen/main.go
Goal with this is a very small/minimal PR which won't conflict with either Relay v1.1 branch, or https://github.com/bluesky-social/indigo/pull/967
This doesn't deprecate/remove anything, just adds cborgen for existing lexicon types, and callbacks for event handlers.
=> add sync event

cmd/goat/firehose.go, cmd/goat/repo.go, cmd/goat/repo_prettyprint.go
This is basically stacked on two other PRs:
- https://github.com/bluesky-social/indigo/pull/983
- https://github.com/bluesky-social/indigo/pull/984
=> update `goat` to work with sync v1.1

cmd/goat/firehose.go, cmd/goat/main.go, cmd/goat/relay.go, cmd/goat/relay_admin.go
```
goat relay admin host list | jq .Host -r
truffle.us-east.host.bsky.network
pds.robocracy.org
grisette.us-west.host.bsky.network
pds.haileyok.com
agaric.us-west.host.bsky.network
pioppino.us-west.host.bsky.network
[...]
```
```
goat relay admin account takedown --reverse bnewbold.net
go run ./cmd/goat/ relay host add pds.example.com
```
```
goat relay account list --json | head
{"did":"did:plc:bpurujb3biqxm3rj6dq362co","head":"bafyreibdp33fixrpjztokl3yjhsfitha7iakfqoddpodhzy3lxqm4e7bi4","rev":""}
{"did":"did:plc:byrvqzvjg2wecnaw5wj42tbn","head":"bafyreiadhjx3h7wmeiolzagxxpd2s3sikypcnnrmkwzrfe6t42qo3vm4ki","rev":""}
{"did":"did:plc:x7hvipgsf3olqj2scs6vnfsx","head":"bafyreidagggvucwh5tieuj5erw4xfkh2y7evpidryp3mof6vnqmx7r42mu","rev":""} …
```
=> relay admin helper commands

splitter/splitter.go
--splitter-host should work for any http/https/ws/wss url
=> cleanup rainbow upstream url handling

search/indexing.go, search/parse_query.go
make function comment match function name
=> chore: make function comment match function name

atproto/repo/car.go, atproto/repo/cmd/repo-tool/main.go, atproto/repo/sync.go, atproto/repo/sync_test.go, cmd/goat/firehose.go, cmd/goat/repo.go, cmd/relay/bgs/validator.go
This only touches code I am developing, so will probably self-merge
=> rename `atproto/repo` CAR loading function names

cmd/collectiondir/README.md, cmd/collectiondir/serve.go
This isn't a full pass, just fixing some known issues:
- process wasn't shutting down with Ctrl-C because of a WaitGroup. fixed the bug, but didn't clean up the (many) channels+goroutines
- many API response errors were strings, not the expected XRPC JSON message format
- README didn't describe the actual API endpoint
=> some collectiondir fixes

atproto/data/blob.go, atproto/lexicon/language.go
I assumed this worked, but it doesn't!
Found via golangci-lint.
=> remove invalid JSON 'const=' struct field tags

cmd/relay/handlers.go, cmd/relay/relay/models/models.go
=> relay tweaks: JSON fields for db models, and fix some API endpoints

cmd/goat/plc.go
=> goat: more plc dump args/ergonomics

cmd/relay/README.md, cmd/relay/handlers.go, cmd/relay/handlers_admin.go, cmd/relay/main.go, cmd/relay/relay/host.go, cmd/relay/relay/relay.go, cmd/relay/relay/slurper.go, cmd/relay/service.go, cmd/relay/stubs.go, splitter/handlers.go
=> yet more relay patches and tweaks

cmd/goat/account.go, cmd/goat/account_migrate.go, cmd/goat/auth.go, cmd/goat/blob.go, cmd/goat/firehose.go, cmd/goat/lexicon.go, cmd/goat/net.go, cmd/goat/pds.go, cmd/goat/plc.go, cmd/goat/record.go, cmd/goat/relay.go, cmd/goat/relay_admin.go, cmd/goat/repo.go, cmd/goat/util.go
Pretty simple, will self-merge.
=> goat: include User-Agent header more consistently

api/bsky/notificationdefs.go
re: https://github.com/bluesky-social/atproto/pull/3966
Ran `make lexgen` and just kept stuff related to notification preferences.
=> Rename Notif Preference Filter -> Include

api/agnostic/doc.go, search/parse_query.go
Description:
This pull request corrects minor typos in documentation and inline comments to improve clarity and maintain code quality.
=> Minor Typo Fixes in Documentation and Comments

carstore/repo_test.go, go.mod, go.sum
I'm going to self-merge this to unblock a project
=> comment out old repo benchmark code using broken dep

atproto/auth/oauth/memstore.go, atproto/auth/oauth/store.go
Just making some implicit things explicit
=> OAuth ClientAuthStore doc tweaks
